// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blueprints.proto

package com.sagas.meta.model;

public final class Blueprints {
  private Blueprints() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BlueOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BlueOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BlueMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BlueMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BotMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BotMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BotRecipient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BotRecipient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BotSetSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BotSetSlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BotAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BotAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_BlueInteract_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_BlueInteract_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020blueprints.proto\022\005model\032\014values.proto\"" +
      "(\n\tBlueOffer\022\014\n\004user\030\001 \001(\t\022\r\n\005offer\030\002 \001(" +
      "\003\"<\n\013BlueMessage\022\021\n\tactorPath\030\001 \001(\t\022\014\n\004t" +
      "ype\030\002 \001(\t\022\014\n\004body\030\003 \001(\014\"i\n\nBotMessage\022\016\n" +
      "\006sender\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\023\n\013attach" +
      "ments\030\003 \003(\t\022%\n\005slots\030\004 \001(\0132\026.model.TaStr" +
      "ingEntries\"(\n\014BotRecipient\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004text\030\002 \001(\t\"6\n\013BotResponse\022\'\n\nrecipient" +
      "s\030\001 \003(\0132\023.model.BotRecipient\"8\n\nBotSetSl" +
      "ot\022\r\n\005event\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005value" +
      "\030\003 \001(\t\",\n\006BotAck\022\021\n\terrorCode\030\001 \001(\005\022\017\n\007m" +
      "essage\030\002 \001(\t\"\036\n\013PingRequest\022\017\n\007message\030\001" +
      " \001(\t\" \n\014PingResponse\022\020\n\010response\030\001 \001(\t\"7" +
      "\n\014BlueInteract\022\013\n\003uri\030\001 \001(\t\022\014\n\004type\030\002 \001(" +
      "\t\022\014\n\004body\030\003 \001(\0142\244\001\n\017ArtifactService\0221\n\004P" +
      "ing\022\022.model.PingRequest\032\023.model.PingResp" +
      "onse\"\000\022/\n\004Talk\022\021.model.BotMessage\032\022.mode" +
      "l.BotResponse\"\000\022-\n\007SetSlot\022\021.model.BotSe" +
      "tSlot\032\r.model.BotAck\"\000B\030\n\024com.sagas.meta" +
      ".modelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sagas.meta.model.Values.getDescriptor(),
        }, assigner);
    internal_static_model_BlueOffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_BlueOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BlueOffer_descriptor,
        new java.lang.String[] { "User", "Offer", });
    internal_static_model_BlueMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_BlueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BlueMessage_descriptor,
        new java.lang.String[] { "ActorPath", "Type", "Body", });
    internal_static_model_BotMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_BotMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BotMessage_descriptor,
        new java.lang.String[] { "Sender", "Message", "Attachments", "Slots", });
    internal_static_model_BotRecipient_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_model_BotRecipient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BotRecipient_descriptor,
        new java.lang.String[] { "Id", "Text", });
    internal_static_model_BotResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_model_BotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BotResponse_descriptor,
        new java.lang.String[] { "Recipients", });
    internal_static_model_BotSetSlot_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_model_BotSetSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BotSetSlot_descriptor,
        new java.lang.String[] { "Event", "Name", "Value", });
    internal_static_model_BotAck_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_model_BotAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BotAck_descriptor,
        new java.lang.String[] { "ErrorCode", "Message", });
    internal_static_model_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_model_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_PingRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_model_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_model_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_PingResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_model_BlueInteract_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_model_BlueInteract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_BlueInteract_descriptor,
        new java.lang.String[] { "Uri", "Type", "Body", });
    com.sagas.meta.model.Values.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
