// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blueprints.proto

package com.sagas.meta.model;

public interface BlueMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.BlueMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string actorPath = 1;</code>
   */
  java.lang.String getActorPath();
  /**
   * <code>string actorPath = 1;</code>
   */
  com.google.protobuf.ByteString
      getActorPathBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes body = 3;</code>
   */
  com.google.protobuf.ByteString getBody();
}
