// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blueprints.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.BotMessage}
 */
public  final class BotMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.BotMessage)
    BotMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BotMessage.newBuilder() to construct.
  private BotMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BotMessage() {
    sender_ = "";
    message_ = "";
    attachments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BotMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sender_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              attachments_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            attachments_.add(s);
            break;
          }
          case 34: {
            com.sagas.meta.model.TaStringEntries.Builder subBuilder = null;
            if (slots_ != null) {
              subBuilder = slots_.toBuilder();
            }
            slots_ = input.readMessage(com.sagas.meta.model.TaStringEntries.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(slots_);
              slots_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        attachments_ = attachments_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Blueprints.internal_static_model_BotMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Blueprints.internal_static_model_BotMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.BotMessage.class, com.sagas.meta.model.BotMessage.Builder.class);
  }

  private int bitField0_;
  public static final int SENDER_FIELD_NUMBER = 1;
  private volatile java.lang.Object sender_;
  /**
   * <code>string sender = 1;</code>
   */
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <code>string sender = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACHMENTS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList attachments_;
  /**
   * <code>repeated string attachments = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAttachmentsList() {
    return attachments_;
  }
  /**
   * <code>repeated string attachments = 3;</code>
   */
  public int getAttachmentsCount() {
    return attachments_.size();
  }
  /**
   * <code>repeated string attachments = 3;</code>
   */
  public java.lang.String getAttachments(int index) {
    return attachments_.get(index);
  }
  /**
   * <code>repeated string attachments = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAttachmentsBytes(int index) {
    return attachments_.getByteString(index);
  }

  public static final int SLOTS_FIELD_NUMBER = 4;
  private com.sagas.meta.model.TaStringEntries slots_;
  /**
   * <code>.model.TaStringEntries slots = 4;</code>
   */
  public boolean hasSlots() {
    return slots_ != null;
  }
  /**
   * <code>.model.TaStringEntries slots = 4;</code>
   */
  public com.sagas.meta.model.TaStringEntries getSlots() {
    return slots_ == null ? com.sagas.meta.model.TaStringEntries.getDefaultInstance() : slots_;
  }
  /**
   * <code>.model.TaStringEntries slots = 4;</code>
   */
  public com.sagas.meta.model.TaStringEntriesOrBuilder getSlotsOrBuilder() {
    return getSlots();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < attachments_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, attachments_.getRaw(i));
    }
    if (slots_ != null) {
      output.writeMessage(4, getSlots());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < attachments_.size(); i++) {
        dataSize += computeStringSizeNoTag(attachments_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAttachmentsList().size();
    }
    if (slots_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSlots());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.BotMessage)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.BotMessage other = (com.sagas.meta.model.BotMessage) obj;

    boolean result = true;
    result = result && getSender()
        .equals(other.getSender());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getAttachmentsList()
        .equals(other.getAttachmentsList());
    result = result && (hasSlots() == other.hasSlots());
    if (hasSlots()) {
      result = result && getSlots()
          .equals(other.getSlots());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getAttachmentsCount() > 0) {
      hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAttachmentsList().hashCode();
    }
    if (hasSlots()) {
      hash = (37 * hash) + SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + getSlots().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.BotMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.BotMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.BotMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.BotMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.BotMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.BotMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.BotMessage)
      com.sagas.meta.model.BotMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Blueprints.internal_static_model_BotMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Blueprints.internal_static_model_BotMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.BotMessage.class, com.sagas.meta.model.BotMessage.Builder.class);
    }

    // Construct using com.sagas.meta.model.BotMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sender_ = "";

      message_ = "";

      attachments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (slotsBuilder_ == null) {
        slots_ = null;
      } else {
        slots_ = null;
        slotsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Blueprints.internal_static_model_BotMessage_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.BotMessage getDefaultInstanceForType() {
      return com.sagas.meta.model.BotMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.BotMessage build() {
      com.sagas.meta.model.BotMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.BotMessage buildPartial() {
      com.sagas.meta.model.BotMessage result = new com.sagas.meta.model.BotMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.sender_ = sender_;
      result.message_ = message_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        attachments_ = attachments_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.attachments_ = attachments_;
      if (slotsBuilder_ == null) {
        result.slots_ = slots_;
      } else {
        result.slots_ = slotsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.BotMessage) {
        return mergeFrom((com.sagas.meta.model.BotMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.BotMessage other) {
      if (other == com.sagas.meta.model.BotMessage.getDefaultInstance()) return this;
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.attachments_.isEmpty()) {
        if (attachments_.isEmpty()) {
          attachments_ = other.attachments_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureAttachmentsIsMutable();
          attachments_.addAll(other.attachments_);
        }
        onChanged();
      }
      if (other.hasSlots()) {
        mergeSlots(other.getSlots());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.BotMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.BotMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object sender_ = "";
    /**
     * <code>string sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender = 1;</code>
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 1;</code>
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 1;</code>
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList attachments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAttachmentsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        attachments_ = new com.google.protobuf.LazyStringArrayList(attachments_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAttachmentsList() {
      return attachments_.getUnmodifiableView();
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public int getAttachmentsCount() {
      return attachments_.size();
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public java.lang.String getAttachments(int index) {
      return attachments_.get(index);
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAttachmentsBytes(int index) {
      return attachments_.getByteString(index);
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public Builder setAttachments(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAttachmentsIsMutable();
      attachments_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public Builder addAttachments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAttachmentsIsMutable();
      attachments_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public Builder addAllAttachments(
        java.lang.Iterable<java.lang.String> values) {
      ensureAttachmentsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, attachments_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public Builder clearAttachments() {
      attachments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attachments = 3;</code>
     */
    public Builder addAttachmentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAttachmentsIsMutable();
      attachments_.add(value);
      onChanged();
      return this;
    }

    private com.sagas.meta.model.TaStringEntries slots_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sagas.meta.model.TaStringEntries, com.sagas.meta.model.TaStringEntries.Builder, com.sagas.meta.model.TaStringEntriesOrBuilder> slotsBuilder_;
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public boolean hasSlots() {
      return slotsBuilder_ != null || slots_ != null;
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public com.sagas.meta.model.TaStringEntries getSlots() {
      if (slotsBuilder_ == null) {
        return slots_ == null ? com.sagas.meta.model.TaStringEntries.getDefaultInstance() : slots_;
      } else {
        return slotsBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public Builder setSlots(com.sagas.meta.model.TaStringEntries value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        slots_ = value;
        onChanged();
      } else {
        slotsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public Builder setSlots(
        com.sagas.meta.model.TaStringEntries.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        slots_ = builderForValue.build();
        onChanged();
      } else {
        slotsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public Builder mergeSlots(com.sagas.meta.model.TaStringEntries value) {
      if (slotsBuilder_ == null) {
        if (slots_ != null) {
          slots_ =
            com.sagas.meta.model.TaStringEntries.newBuilder(slots_).mergeFrom(value).buildPartial();
        } else {
          slots_ = value;
        }
        onChanged();
      } else {
        slotsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public Builder clearSlots() {
      if (slotsBuilder_ == null) {
        slots_ = null;
        onChanged();
      } else {
        slots_ = null;
        slotsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public com.sagas.meta.model.TaStringEntries.Builder getSlotsBuilder() {
      
      onChanged();
      return getSlotsFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    public com.sagas.meta.model.TaStringEntriesOrBuilder getSlotsOrBuilder() {
      if (slotsBuilder_ != null) {
        return slotsBuilder_.getMessageOrBuilder();
      } else {
        return slots_ == null ?
            com.sagas.meta.model.TaStringEntries.getDefaultInstance() : slots_;
      }
    }
    /**
     * <code>.model.TaStringEntries slots = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sagas.meta.model.TaStringEntries, com.sagas.meta.model.TaStringEntries.Builder, com.sagas.meta.model.TaStringEntriesOrBuilder> 
        getSlotsFieldBuilder() {
      if (slotsBuilder_ == null) {
        slotsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sagas.meta.model.TaStringEntries, com.sagas.meta.model.TaStringEntries.Builder, com.sagas.meta.model.TaStringEntriesOrBuilder>(
                getSlots(),
                getParentForChildren(),
                isClean());
        slots_ = null;
      }
      return slotsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.BotMessage)
  }

  // @@protoc_insertion_point(class_scope:model.BotMessage)
  private static final com.sagas.meta.model.BotMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.BotMessage();
  }

  public static com.sagas.meta.model.BotMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BotMessage>
      PARSER = new com.google.protobuf.AbstractParser<BotMessage>() {
    @java.lang.Override
    public BotMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BotMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BotMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BotMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.BotMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

