// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blueprints.proto

package com.sagas.meta.model;

public interface BotSetSlotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.BotSetSlot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event = 1;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
