// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services_common.proto

package com.sagas.meta.model;

public interface InfoMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.InfoMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; info = 1;</code>
   */
  int getInfoCount();
  /**
   * <code>map&lt;string, string&gt; info = 1;</code>
   */
  boolean containsInfo(
      java.lang.String key);
  /**
   * Use {@link #getInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getInfo();
  /**
   * <code>map&lt;string, string&gt; info = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getInfoMap();
  /**
   * <code>map&lt;string, string&gt; info = 1;</code>
   */

  java.lang.String getInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; info = 1;</code>
   */

  java.lang.String getInfoOrThrow(
      java.lang.String key);
}
