// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services_common.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.InfoQuery}
 */
public  final class InfoQuery extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.InfoQuery)
    InfoQueryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoQuery.newBuilder() to construct.
  private InfoQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoQuery() {
    queryItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoQuery(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              queryItems_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            queryItems_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        queryItems_ = queryItems_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.ServicesCommon.internal_static_model_InfoQuery_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.ServicesCommon.internal_static_model_InfoQuery_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.InfoQuery.class, com.sagas.meta.model.InfoQuery.Builder.class);
  }

  public static final int QUERYITEMS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList queryItems_;
  /**
   * <code>repeated string queryItems = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getQueryItemsList() {
    return queryItems_;
  }
  /**
   * <code>repeated string queryItems = 1;</code>
   */
  public int getQueryItemsCount() {
    return queryItems_.size();
  }
  /**
   * <code>repeated string queryItems = 1;</code>
   */
  public java.lang.String getQueryItems(int index) {
    return queryItems_.get(index);
  }
  /**
   * <code>repeated string queryItems = 1;</code>
   */
  public com.google.protobuf.ByteString
      getQueryItemsBytes(int index) {
    return queryItems_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < queryItems_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queryItems_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < queryItems_.size(); i++) {
        dataSize += computeStringSizeNoTag(queryItems_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getQueryItemsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.InfoQuery)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.InfoQuery other = (com.sagas.meta.model.InfoQuery) obj;

    boolean result = true;
    result = result && getQueryItemsList()
        .equals(other.getQueryItemsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getQueryItemsCount() > 0) {
      hash = (37 * hash) + QUERYITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getQueryItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.InfoQuery parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.InfoQuery parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.InfoQuery parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.InfoQuery parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.InfoQuery prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.InfoQuery}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.InfoQuery)
      com.sagas.meta.model.InfoQueryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.ServicesCommon.internal_static_model_InfoQuery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.ServicesCommon.internal_static_model_InfoQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.InfoQuery.class, com.sagas.meta.model.InfoQuery.Builder.class);
    }

    // Construct using com.sagas.meta.model.InfoQuery.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      queryItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.ServicesCommon.internal_static_model_InfoQuery_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.InfoQuery getDefaultInstanceForType() {
      return com.sagas.meta.model.InfoQuery.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.InfoQuery build() {
      com.sagas.meta.model.InfoQuery result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.InfoQuery buildPartial() {
      com.sagas.meta.model.InfoQuery result = new com.sagas.meta.model.InfoQuery(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        queryItems_ = queryItems_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.queryItems_ = queryItems_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.InfoQuery) {
        return mergeFrom((com.sagas.meta.model.InfoQuery)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.InfoQuery other) {
      if (other == com.sagas.meta.model.InfoQuery.getDefaultInstance()) return this;
      if (!other.queryItems_.isEmpty()) {
        if (queryItems_.isEmpty()) {
          queryItems_ = other.queryItems_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureQueryItemsIsMutable();
          queryItems_.addAll(other.queryItems_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.InfoQuery parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.InfoQuery) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList queryItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureQueryItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        queryItems_ = new com.google.protobuf.LazyStringArrayList(queryItems_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getQueryItemsList() {
      return queryItems_.getUnmodifiableView();
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public int getQueryItemsCount() {
      return queryItems_.size();
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public java.lang.String getQueryItems(int index) {
      return queryItems_.get(index);
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryItemsBytes(int index) {
      return queryItems_.getByteString(index);
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public Builder setQueryItems(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureQueryItemsIsMutable();
      queryItems_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public Builder addQueryItems(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureQueryItemsIsMutable();
      queryItems_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public Builder addAllQueryItems(
        java.lang.Iterable<java.lang.String> values) {
      ensureQueryItemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, queryItems_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public Builder clearQueryItems() {
      queryItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string queryItems = 1;</code>
     */
    public Builder addQueryItemsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureQueryItemsIsMutable();
      queryItems_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.InfoQuery)
  }

  // @@protoc_insertion_point(class_scope:model.InfoQuery)
  private static final com.sagas.meta.model.InfoQuery DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.InfoQuery();
  }

  public static com.sagas.meta.model.InfoQuery getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoQuery>
      PARSER = new com.google.protobuf.AbstractParser<InfoQuery>() {
    @java.lang.Override
    public InfoQuery parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InfoQuery(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoQuery> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoQuery> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.InfoQuery getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

