// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

public interface MetaMemberEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaMemberEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entityAlias = 1;</code>
   */
  java.lang.String getEntityAlias();
  /**
   * <code>string entityAlias = 1;</code>
   */
  com.google.protobuf.ByteString
      getEntityAliasBytes();

  /**
   * <code>string entityName = 2;</code>
   */
  java.lang.String getEntityName();
  /**
   * <code>string entityName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEntityNameBytes();
}
