// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.MetaViewEntity}
 */
public  final class MetaViewEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.MetaViewEntity)
    MetaViewEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaViewEntity.newBuilder() to construct.
  private MetaViewEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaViewEntity() {
    entityName_ = "";
    packageName_ = "";
    aliasAlls_ = java.util.Collections.emptyList();
    aliases_ = java.util.Collections.emptyList();
    viewLinks_ = java.util.Collections.emptyList();
    groupBys_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetaViewEntity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            entityName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              memberModelEntities_ = com.google.protobuf.MapField.newMapField(
                  MemberModelEntitiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
            memberModelEntities__ = input.readMessage(
                MemberModelEntitiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            memberModelEntities_.getMutableMap().put(
                memberModelEntities__.getKey(), memberModelEntities__.getValue());
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              aliasAlls_ = new java.util.ArrayList<com.sagas.meta.model.MetaAliasAll>();
              mutable_bitField0_ |= 0x00000008;
            }
            aliasAlls_.add(
                input.readMessage(com.sagas.meta.model.MetaAliasAll.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              aliases_ = new java.util.ArrayList<com.sagas.meta.model.MetaAlias>();
              mutable_bitField0_ |= 0x00000010;
            }
            aliases_.add(
                input.readMessage(com.sagas.meta.model.MetaAlias.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              viewLinks_ = new java.util.ArrayList<com.sagas.meta.model.MetaViewLink>();
              mutable_bitField0_ |= 0x00000020;
            }
            viewLinks_.add(
                input.readMessage(com.sagas.meta.model.MetaViewLink.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              groupBys_ = new java.util.ArrayList<com.sagas.meta.model.MetaField>();
              mutable_bitField0_ |= 0x00000040;
            }
            groupBys_.add(
                input.readMessage(com.sagas.meta.model.MetaField.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        aliasAlls_ = java.util.Collections.unmodifiableList(aliasAlls_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        aliases_ = java.util.Collections.unmodifiableList(aliases_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        viewLinks_ = java.util.Collections.unmodifiableList(viewLinks_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        groupBys_ = java.util.Collections.unmodifiableList(groupBys_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetMemberModelEntities();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.MetaViewEntity.class, com.sagas.meta.model.MetaViewEntity.Builder.class);
  }

  private int bitField0_;
  public static final int ENTITYNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object entityName_;
  /**
   * <pre>
   *&#47; entity properties
   * </pre>
   *
   * <code>string entityName = 1;</code>
   */
  public java.lang.String getEntityName() {
    java.lang.Object ref = entityName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; entity properties
   * </pre>
   *
   * <code>string entityName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEntityNameBytes() {
    java.lang.Object ref = entityName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object packageName_;
  /**
   * <code>string packageName = 2;</code>
   */
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <code>string packageName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBERMODELENTITIES_FIELD_NUMBER = 3;
  private static final class MemberModelEntitiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.sagas.meta.model.MetaMemberEntity> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.sagas.meta.model.MetaMemberEntity>newDefaultInstance(
                com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_MemberModelEntitiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.sagas.meta.model.MetaMemberEntity.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.sagas.meta.model.MetaMemberEntity> memberModelEntities_;
  private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
  internalGetMemberModelEntities() {
    if (memberModelEntities_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MemberModelEntitiesDefaultEntryHolder.defaultEntry);
    }
    return memberModelEntities_;
  }

  public int getMemberModelEntitiesCount() {
    return internalGetMemberModelEntities().getMap().size();
  }
  /**
   * <pre>
   * view
   * </pre>
   *
   * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
   */

  public boolean containsMemberModelEntities(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMemberModelEntities().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMemberModelEntitiesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> getMemberModelEntities() {
    return getMemberModelEntitiesMap();
  }
  /**
   * <pre>
   * view
   * </pre>
   *
   * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
   */

  public java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> getMemberModelEntitiesMap() {
    return internalGetMemberModelEntities().getMap();
  }
  /**
   * <pre>
   * view
   * </pre>
   *
   * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
   */

  public com.sagas.meta.model.MetaMemberEntity getMemberModelEntitiesOrDefault(
      java.lang.String key,
      com.sagas.meta.model.MetaMemberEntity defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> map =
        internalGetMemberModelEntities().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * view
   * </pre>
   *
   * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
   */

  public com.sagas.meta.model.MetaMemberEntity getMemberModelEntitiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> map =
        internalGetMemberModelEntities().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ALIASALLS_FIELD_NUMBER = 4;
  private java.util.List<com.sagas.meta.model.MetaAliasAll> aliasAlls_;
  /**
   * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
   */
  public java.util.List<com.sagas.meta.model.MetaAliasAll> getAliasAllsList() {
    return aliasAlls_;
  }
  /**
   * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
   */
  public java.util.List<? extends com.sagas.meta.model.MetaAliasAllOrBuilder> 
      getAliasAllsOrBuilderList() {
    return aliasAlls_;
  }
  /**
   * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
   */
  public int getAliasAllsCount() {
    return aliasAlls_.size();
  }
  /**
   * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
   */
  public com.sagas.meta.model.MetaAliasAll getAliasAlls(int index) {
    return aliasAlls_.get(index);
  }
  /**
   * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
   */
  public com.sagas.meta.model.MetaAliasAllOrBuilder getAliasAllsOrBuilder(
      int index) {
    return aliasAlls_.get(index);
  }

  public static final int ALIASES_FIELD_NUMBER = 5;
  private java.util.List<com.sagas.meta.model.MetaAlias> aliases_;
  /**
   * <code>repeated .model.MetaAlias aliases = 5;</code>
   */
  public java.util.List<com.sagas.meta.model.MetaAlias> getAliasesList() {
    return aliases_;
  }
  /**
   * <code>repeated .model.MetaAlias aliases = 5;</code>
   */
  public java.util.List<? extends com.sagas.meta.model.MetaAliasOrBuilder> 
      getAliasesOrBuilderList() {
    return aliases_;
  }
  /**
   * <code>repeated .model.MetaAlias aliases = 5;</code>
   */
  public int getAliasesCount() {
    return aliases_.size();
  }
  /**
   * <code>repeated .model.MetaAlias aliases = 5;</code>
   */
  public com.sagas.meta.model.MetaAlias getAliases(int index) {
    return aliases_.get(index);
  }
  /**
   * <code>repeated .model.MetaAlias aliases = 5;</code>
   */
  public com.sagas.meta.model.MetaAliasOrBuilder getAliasesOrBuilder(
      int index) {
    return aliases_.get(index);
  }

  public static final int VIEWLINKS_FIELD_NUMBER = 6;
  private java.util.List<com.sagas.meta.model.MetaViewLink> viewLinks_;
  /**
   * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
   */
  public java.util.List<com.sagas.meta.model.MetaViewLink> getViewLinksList() {
    return viewLinks_;
  }
  /**
   * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
   */
  public java.util.List<? extends com.sagas.meta.model.MetaViewLinkOrBuilder> 
      getViewLinksOrBuilderList() {
    return viewLinks_;
  }
  /**
   * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
   */
  public int getViewLinksCount() {
    return viewLinks_.size();
  }
  /**
   * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
   */
  public com.sagas.meta.model.MetaViewLink getViewLinks(int index) {
    return viewLinks_.get(index);
  }
  /**
   * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
   */
  public com.sagas.meta.model.MetaViewLinkOrBuilder getViewLinksOrBuilder(
      int index) {
    return viewLinks_.get(index);
  }

  public static final int GROUPBYS_FIELD_NUMBER = 7;
  private java.util.List<com.sagas.meta.model.MetaField> groupBys_;
  /**
   * <code>repeated .model.MetaField groupBys = 7;</code>
   */
  public java.util.List<com.sagas.meta.model.MetaField> getGroupBysList() {
    return groupBys_;
  }
  /**
   * <code>repeated .model.MetaField groupBys = 7;</code>
   */
  public java.util.List<? extends com.sagas.meta.model.MetaFieldOrBuilder> 
      getGroupBysOrBuilderList() {
    return groupBys_;
  }
  /**
   * <code>repeated .model.MetaField groupBys = 7;</code>
   */
  public int getGroupBysCount() {
    return groupBys_.size();
  }
  /**
   * <code>repeated .model.MetaField groupBys = 7;</code>
   */
  public com.sagas.meta.model.MetaField getGroupBys(int index) {
    return groupBys_.get(index);
  }
  /**
   * <code>repeated .model.MetaField groupBys = 7;</code>
   */
  public com.sagas.meta.model.MetaFieldOrBuilder getGroupBysOrBuilder(
      int index) {
    return groupBys_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEntityNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entityName_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageName_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMemberModelEntities(),
        MemberModelEntitiesDefaultEntryHolder.defaultEntry,
        3);
    for (int i = 0; i < aliasAlls_.size(); i++) {
      output.writeMessage(4, aliasAlls_.get(i));
    }
    for (int i = 0; i < aliases_.size(); i++) {
      output.writeMessage(5, aliases_.get(i));
    }
    for (int i = 0; i < viewLinks_.size(); i++) {
      output.writeMessage(6, viewLinks_.get(i));
    }
    for (int i = 0; i < groupBys_.size(); i++) {
      output.writeMessage(7, groupBys_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEntityNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entityName_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, packageName_);
    }
    for (java.util.Map.Entry<java.lang.String, com.sagas.meta.model.MetaMemberEntity> entry
         : internalGetMemberModelEntities().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
      memberModelEntities__ = MemberModelEntitiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, memberModelEntities__);
    }
    for (int i = 0; i < aliasAlls_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, aliasAlls_.get(i));
    }
    for (int i = 0; i < aliases_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, aliases_.get(i));
    }
    for (int i = 0; i < viewLinks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, viewLinks_.get(i));
    }
    for (int i = 0; i < groupBys_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, groupBys_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.MetaViewEntity)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.MetaViewEntity other = (com.sagas.meta.model.MetaViewEntity) obj;

    boolean result = true;
    result = result && getEntityName()
        .equals(other.getEntityName());
    result = result && getPackageName()
        .equals(other.getPackageName());
    result = result && internalGetMemberModelEntities().equals(
        other.internalGetMemberModelEntities());
    result = result && getAliasAllsList()
        .equals(other.getAliasAllsList());
    result = result && getAliasesList()
        .equals(other.getAliasesList());
    result = result && getViewLinksList()
        .equals(other.getViewLinksList());
    result = result && getGroupBysList()
        .equals(other.getGroupBysList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEntityName().hashCode();
    hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    if (!internalGetMemberModelEntities().getMap().isEmpty()) {
      hash = (37 * hash) + MEMBERMODELENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMemberModelEntities().hashCode();
    }
    if (getAliasAllsCount() > 0) {
      hash = (37 * hash) + ALIASALLS_FIELD_NUMBER;
      hash = (53 * hash) + getAliasAllsList().hashCode();
    }
    if (getAliasesCount() > 0) {
      hash = (37 * hash) + ALIASES_FIELD_NUMBER;
      hash = (53 * hash) + getAliasesList().hashCode();
    }
    if (getViewLinksCount() > 0) {
      hash = (37 * hash) + VIEWLINKS_FIELD_NUMBER;
      hash = (53 * hash) + getViewLinksList().hashCode();
    }
    if (getGroupBysCount() > 0) {
      hash = (37 * hash) + GROUPBYS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupBysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.MetaViewEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.MetaViewEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.MetaViewEntity)
      com.sagas.meta.model.MetaViewEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMemberModelEntities();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableMemberModelEntities();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.MetaViewEntity.class, com.sagas.meta.model.MetaViewEntity.Builder.class);
    }

    // Construct using com.sagas.meta.model.MetaViewEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAliasAllsFieldBuilder();
        getAliasesFieldBuilder();
        getViewLinksFieldBuilder();
        getGroupBysFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      entityName_ = "";

      packageName_ = "";

      internalGetMutableMemberModelEntities().clear();
      if (aliasAllsBuilder_ == null) {
        aliasAlls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        aliasAllsBuilder_.clear();
      }
      if (aliasesBuilder_ == null) {
        aliases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        aliasesBuilder_.clear();
      }
      if (viewLinksBuilder_ == null) {
        viewLinks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        viewLinksBuilder_.clear();
      }
      if (groupBysBuilder_ == null) {
        groupBys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        groupBysBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewEntity_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewEntity getDefaultInstanceForType() {
      return com.sagas.meta.model.MetaViewEntity.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewEntity build() {
      com.sagas.meta.model.MetaViewEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewEntity buildPartial() {
      com.sagas.meta.model.MetaViewEntity result = new com.sagas.meta.model.MetaViewEntity(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.entityName_ = entityName_;
      result.packageName_ = packageName_;
      result.memberModelEntities_ = internalGetMemberModelEntities();
      result.memberModelEntities_.makeImmutable();
      if (aliasAllsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          aliasAlls_ = java.util.Collections.unmodifiableList(aliasAlls_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.aliasAlls_ = aliasAlls_;
      } else {
        result.aliasAlls_ = aliasAllsBuilder_.build();
      }
      if (aliasesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          aliases_ = java.util.Collections.unmodifiableList(aliases_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.aliases_ = aliases_;
      } else {
        result.aliases_ = aliasesBuilder_.build();
      }
      if (viewLinksBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          viewLinks_ = java.util.Collections.unmodifiableList(viewLinks_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.viewLinks_ = viewLinks_;
      } else {
        result.viewLinks_ = viewLinksBuilder_.build();
      }
      if (groupBysBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          groupBys_ = java.util.Collections.unmodifiableList(groupBys_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.groupBys_ = groupBys_;
      } else {
        result.groupBys_ = groupBysBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.MetaViewEntity) {
        return mergeFrom((com.sagas.meta.model.MetaViewEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.MetaViewEntity other) {
      if (other == com.sagas.meta.model.MetaViewEntity.getDefaultInstance()) return this;
      if (!other.getEntityName().isEmpty()) {
        entityName_ = other.entityName_;
        onChanged();
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      internalGetMutableMemberModelEntities().mergeFrom(
          other.internalGetMemberModelEntities());
      if (aliasAllsBuilder_ == null) {
        if (!other.aliasAlls_.isEmpty()) {
          if (aliasAlls_.isEmpty()) {
            aliasAlls_ = other.aliasAlls_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAliasAllsIsMutable();
            aliasAlls_.addAll(other.aliasAlls_);
          }
          onChanged();
        }
      } else {
        if (!other.aliasAlls_.isEmpty()) {
          if (aliasAllsBuilder_.isEmpty()) {
            aliasAllsBuilder_.dispose();
            aliasAllsBuilder_ = null;
            aliasAlls_ = other.aliasAlls_;
            bitField0_ = (bitField0_ & ~0x00000008);
            aliasAllsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAliasAllsFieldBuilder() : null;
          } else {
            aliasAllsBuilder_.addAllMessages(other.aliasAlls_);
          }
        }
      }
      if (aliasesBuilder_ == null) {
        if (!other.aliases_.isEmpty()) {
          if (aliases_.isEmpty()) {
            aliases_ = other.aliases_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureAliasesIsMutable();
            aliases_.addAll(other.aliases_);
          }
          onChanged();
        }
      } else {
        if (!other.aliases_.isEmpty()) {
          if (aliasesBuilder_.isEmpty()) {
            aliasesBuilder_.dispose();
            aliasesBuilder_ = null;
            aliases_ = other.aliases_;
            bitField0_ = (bitField0_ & ~0x00000010);
            aliasesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAliasesFieldBuilder() : null;
          } else {
            aliasesBuilder_.addAllMessages(other.aliases_);
          }
        }
      }
      if (viewLinksBuilder_ == null) {
        if (!other.viewLinks_.isEmpty()) {
          if (viewLinks_.isEmpty()) {
            viewLinks_ = other.viewLinks_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureViewLinksIsMutable();
            viewLinks_.addAll(other.viewLinks_);
          }
          onChanged();
        }
      } else {
        if (!other.viewLinks_.isEmpty()) {
          if (viewLinksBuilder_.isEmpty()) {
            viewLinksBuilder_.dispose();
            viewLinksBuilder_ = null;
            viewLinks_ = other.viewLinks_;
            bitField0_ = (bitField0_ & ~0x00000020);
            viewLinksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getViewLinksFieldBuilder() : null;
          } else {
            viewLinksBuilder_.addAllMessages(other.viewLinks_);
          }
        }
      }
      if (groupBysBuilder_ == null) {
        if (!other.groupBys_.isEmpty()) {
          if (groupBys_.isEmpty()) {
            groupBys_ = other.groupBys_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureGroupBysIsMutable();
            groupBys_.addAll(other.groupBys_);
          }
          onChanged();
        }
      } else {
        if (!other.groupBys_.isEmpty()) {
          if (groupBysBuilder_.isEmpty()) {
            groupBysBuilder_.dispose();
            groupBysBuilder_ = null;
            groupBys_ = other.groupBys_;
            bitField0_ = (bitField0_ & ~0x00000040);
            groupBysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGroupBysFieldBuilder() : null;
          } else {
            groupBysBuilder_.addAllMessages(other.groupBys_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.MetaViewEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.MetaViewEntity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object entityName_ = "";
    /**
     * <pre>
     *&#47; entity properties
     * </pre>
     *
     * <code>string entityName = 1;</code>
     */
    public java.lang.String getEntityName() {
      java.lang.Object ref = entityName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; entity properties
     * </pre>
     *
     * <code>string entityName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEntityNameBytes() {
      java.lang.Object ref = entityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; entity properties
     * </pre>
     *
     * <code>string entityName = 1;</code>
     */
    public Builder setEntityName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entityName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; entity properties
     * </pre>
     *
     * <code>string entityName = 1;</code>
     */
    public Builder clearEntityName() {
      
      entityName_ = getDefaultInstance().getEntityName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; entity properties
     * </pre>
     *
     * <code>string entityName = 1;</code>
     */
    public Builder setEntityNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entityName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <code>string packageName = 2;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string packageName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string packageName = 2;</code>
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string packageName = 2;</code>
     */
    public Builder clearPackageName() {
      
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>string packageName = 2;</code>
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.sagas.meta.model.MetaMemberEntity> memberModelEntities_;
    private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
    internalGetMemberModelEntities() {
      if (memberModelEntities_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MemberModelEntitiesDefaultEntryHolder.defaultEntry);
      }
      return memberModelEntities_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
    internalGetMutableMemberModelEntities() {
      onChanged();;
      if (memberModelEntities_ == null) {
        memberModelEntities_ = com.google.protobuf.MapField.newMapField(
            MemberModelEntitiesDefaultEntryHolder.defaultEntry);
      }
      if (!memberModelEntities_.isMutable()) {
        memberModelEntities_ = memberModelEntities_.copy();
      }
      return memberModelEntities_;
    }

    public int getMemberModelEntitiesCount() {
      return internalGetMemberModelEntities().getMap().size();
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public boolean containsMemberModelEntities(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMemberModelEntities().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMemberModelEntitiesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> getMemberModelEntities() {
      return getMemberModelEntitiesMap();
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> getMemberModelEntitiesMap() {
      return internalGetMemberModelEntities().getMap();
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public com.sagas.meta.model.MetaMemberEntity getMemberModelEntitiesOrDefault(
        java.lang.String key,
        com.sagas.meta.model.MetaMemberEntity defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> map =
          internalGetMemberModelEntities().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public com.sagas.meta.model.MetaMemberEntity getMemberModelEntitiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> map =
          internalGetMemberModelEntities().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMemberModelEntities() {
      internalGetMutableMemberModelEntities().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public Builder removeMemberModelEntities(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMemberModelEntities().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity>
    getMutableMemberModelEntities() {
      return internalGetMutableMemberModelEntities().getMutableMap();
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */
    public Builder putMemberModelEntities(
        java.lang.String key,
        com.sagas.meta.model.MetaMemberEntity value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMemberModelEntities().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * view
     * </pre>
     *
     * <code>map&lt;string, .model.MetaMemberEntity&gt; memberModelEntities = 3;</code>
     */

    public Builder putAllMemberModelEntities(
        java.util.Map<java.lang.String, com.sagas.meta.model.MetaMemberEntity> values) {
      internalGetMutableMemberModelEntities().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<com.sagas.meta.model.MetaAliasAll> aliasAlls_ =
      java.util.Collections.emptyList();
    private void ensureAliasAllsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        aliasAlls_ = new java.util.ArrayList<com.sagas.meta.model.MetaAliasAll>(aliasAlls_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaAliasAll, com.sagas.meta.model.MetaAliasAll.Builder, com.sagas.meta.model.MetaAliasAllOrBuilder> aliasAllsBuilder_;

    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaAliasAll> getAliasAllsList() {
      if (aliasAllsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aliasAlls_);
      } else {
        return aliasAllsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public int getAliasAllsCount() {
      if (aliasAllsBuilder_ == null) {
        return aliasAlls_.size();
      } else {
        return aliasAllsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public com.sagas.meta.model.MetaAliasAll getAliasAlls(int index) {
      if (aliasAllsBuilder_ == null) {
        return aliasAlls_.get(index);
      } else {
        return aliasAllsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder setAliasAlls(
        int index, com.sagas.meta.model.MetaAliasAll value) {
      if (aliasAllsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasAllsIsMutable();
        aliasAlls_.set(index, value);
        onChanged();
      } else {
        aliasAllsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder setAliasAlls(
        int index, com.sagas.meta.model.MetaAliasAll.Builder builderForValue) {
      if (aliasAllsBuilder_ == null) {
        ensureAliasAllsIsMutable();
        aliasAlls_.set(index, builderForValue.build());
        onChanged();
      } else {
        aliasAllsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder addAliasAlls(com.sagas.meta.model.MetaAliasAll value) {
      if (aliasAllsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasAllsIsMutable();
        aliasAlls_.add(value);
        onChanged();
      } else {
        aliasAllsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder addAliasAlls(
        int index, com.sagas.meta.model.MetaAliasAll value) {
      if (aliasAllsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasAllsIsMutable();
        aliasAlls_.add(index, value);
        onChanged();
      } else {
        aliasAllsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder addAliasAlls(
        com.sagas.meta.model.MetaAliasAll.Builder builderForValue) {
      if (aliasAllsBuilder_ == null) {
        ensureAliasAllsIsMutable();
        aliasAlls_.add(builderForValue.build());
        onChanged();
      } else {
        aliasAllsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder addAliasAlls(
        int index, com.sagas.meta.model.MetaAliasAll.Builder builderForValue) {
      if (aliasAllsBuilder_ == null) {
        ensureAliasAllsIsMutable();
        aliasAlls_.add(index, builderForValue.build());
        onChanged();
      } else {
        aliasAllsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder addAllAliasAlls(
        java.lang.Iterable<? extends com.sagas.meta.model.MetaAliasAll> values) {
      if (aliasAllsBuilder_ == null) {
        ensureAliasAllsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aliasAlls_);
        onChanged();
      } else {
        aliasAllsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder clearAliasAlls() {
      if (aliasAllsBuilder_ == null) {
        aliasAlls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        aliasAllsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public Builder removeAliasAlls(int index) {
      if (aliasAllsBuilder_ == null) {
        ensureAliasAllsIsMutable();
        aliasAlls_.remove(index);
        onChanged();
      } else {
        aliasAllsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public com.sagas.meta.model.MetaAliasAll.Builder getAliasAllsBuilder(
        int index) {
      return getAliasAllsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public com.sagas.meta.model.MetaAliasAllOrBuilder getAliasAllsOrBuilder(
        int index) {
      if (aliasAllsBuilder_ == null) {
        return aliasAlls_.get(index);  } else {
        return aliasAllsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public java.util.List<? extends com.sagas.meta.model.MetaAliasAllOrBuilder> 
         getAliasAllsOrBuilderList() {
      if (aliasAllsBuilder_ != null) {
        return aliasAllsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aliasAlls_);
      }
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public com.sagas.meta.model.MetaAliasAll.Builder addAliasAllsBuilder() {
      return getAliasAllsFieldBuilder().addBuilder(
          com.sagas.meta.model.MetaAliasAll.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public com.sagas.meta.model.MetaAliasAll.Builder addAliasAllsBuilder(
        int index) {
      return getAliasAllsFieldBuilder().addBuilder(
          index, com.sagas.meta.model.MetaAliasAll.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaAliasAll aliasAlls = 4;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaAliasAll.Builder> 
         getAliasAllsBuilderList() {
      return getAliasAllsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaAliasAll, com.sagas.meta.model.MetaAliasAll.Builder, com.sagas.meta.model.MetaAliasAllOrBuilder> 
        getAliasAllsFieldBuilder() {
      if (aliasAllsBuilder_ == null) {
        aliasAllsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sagas.meta.model.MetaAliasAll, com.sagas.meta.model.MetaAliasAll.Builder, com.sagas.meta.model.MetaAliasAllOrBuilder>(
                aliasAlls_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        aliasAlls_ = null;
      }
      return aliasAllsBuilder_;
    }

    private java.util.List<com.sagas.meta.model.MetaAlias> aliases_ =
      java.util.Collections.emptyList();
    private void ensureAliasesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        aliases_ = new java.util.ArrayList<com.sagas.meta.model.MetaAlias>(aliases_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaAlias, com.sagas.meta.model.MetaAlias.Builder, com.sagas.meta.model.MetaAliasOrBuilder> aliasesBuilder_;

    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaAlias> getAliasesList() {
      if (aliasesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aliases_);
      } else {
        return aliasesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public int getAliasesCount() {
      if (aliasesBuilder_ == null) {
        return aliases_.size();
      } else {
        return aliasesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public com.sagas.meta.model.MetaAlias getAliases(int index) {
      if (aliasesBuilder_ == null) {
        return aliases_.get(index);
      } else {
        return aliasesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder setAliases(
        int index, com.sagas.meta.model.MetaAlias value) {
      if (aliasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasesIsMutable();
        aliases_.set(index, value);
        onChanged();
      } else {
        aliasesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder setAliases(
        int index, com.sagas.meta.model.MetaAlias.Builder builderForValue) {
      if (aliasesBuilder_ == null) {
        ensureAliasesIsMutable();
        aliases_.set(index, builderForValue.build());
        onChanged();
      } else {
        aliasesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder addAliases(com.sagas.meta.model.MetaAlias value) {
      if (aliasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasesIsMutable();
        aliases_.add(value);
        onChanged();
      } else {
        aliasesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder addAliases(
        int index, com.sagas.meta.model.MetaAlias value) {
      if (aliasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAliasesIsMutable();
        aliases_.add(index, value);
        onChanged();
      } else {
        aliasesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder addAliases(
        com.sagas.meta.model.MetaAlias.Builder builderForValue) {
      if (aliasesBuilder_ == null) {
        ensureAliasesIsMutable();
        aliases_.add(builderForValue.build());
        onChanged();
      } else {
        aliasesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder addAliases(
        int index, com.sagas.meta.model.MetaAlias.Builder builderForValue) {
      if (aliasesBuilder_ == null) {
        ensureAliasesIsMutable();
        aliases_.add(index, builderForValue.build());
        onChanged();
      } else {
        aliasesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder addAllAliases(
        java.lang.Iterable<? extends com.sagas.meta.model.MetaAlias> values) {
      if (aliasesBuilder_ == null) {
        ensureAliasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aliases_);
        onChanged();
      } else {
        aliasesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder clearAliases() {
      if (aliasesBuilder_ == null) {
        aliases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        aliasesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public Builder removeAliases(int index) {
      if (aliasesBuilder_ == null) {
        ensureAliasesIsMutable();
        aliases_.remove(index);
        onChanged();
      } else {
        aliasesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public com.sagas.meta.model.MetaAlias.Builder getAliasesBuilder(
        int index) {
      return getAliasesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public com.sagas.meta.model.MetaAliasOrBuilder getAliasesOrBuilder(
        int index) {
      if (aliasesBuilder_ == null) {
        return aliases_.get(index);  } else {
        return aliasesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public java.util.List<? extends com.sagas.meta.model.MetaAliasOrBuilder> 
         getAliasesOrBuilderList() {
      if (aliasesBuilder_ != null) {
        return aliasesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aliases_);
      }
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public com.sagas.meta.model.MetaAlias.Builder addAliasesBuilder() {
      return getAliasesFieldBuilder().addBuilder(
          com.sagas.meta.model.MetaAlias.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public com.sagas.meta.model.MetaAlias.Builder addAliasesBuilder(
        int index) {
      return getAliasesFieldBuilder().addBuilder(
          index, com.sagas.meta.model.MetaAlias.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaAlias aliases = 5;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaAlias.Builder> 
         getAliasesBuilderList() {
      return getAliasesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaAlias, com.sagas.meta.model.MetaAlias.Builder, com.sagas.meta.model.MetaAliasOrBuilder> 
        getAliasesFieldBuilder() {
      if (aliasesBuilder_ == null) {
        aliasesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sagas.meta.model.MetaAlias, com.sagas.meta.model.MetaAlias.Builder, com.sagas.meta.model.MetaAliasOrBuilder>(
                aliases_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        aliases_ = null;
      }
      return aliasesBuilder_;
    }

    private java.util.List<com.sagas.meta.model.MetaViewLink> viewLinks_ =
      java.util.Collections.emptyList();
    private void ensureViewLinksIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        viewLinks_ = new java.util.ArrayList<com.sagas.meta.model.MetaViewLink>(viewLinks_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaViewLink, com.sagas.meta.model.MetaViewLink.Builder, com.sagas.meta.model.MetaViewLinkOrBuilder> viewLinksBuilder_;

    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaViewLink> getViewLinksList() {
      if (viewLinksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(viewLinks_);
      } else {
        return viewLinksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public int getViewLinksCount() {
      if (viewLinksBuilder_ == null) {
        return viewLinks_.size();
      } else {
        return viewLinksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public com.sagas.meta.model.MetaViewLink getViewLinks(int index) {
      if (viewLinksBuilder_ == null) {
        return viewLinks_.get(index);
      } else {
        return viewLinksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder setViewLinks(
        int index, com.sagas.meta.model.MetaViewLink value) {
      if (viewLinksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewLinksIsMutable();
        viewLinks_.set(index, value);
        onChanged();
      } else {
        viewLinksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder setViewLinks(
        int index, com.sagas.meta.model.MetaViewLink.Builder builderForValue) {
      if (viewLinksBuilder_ == null) {
        ensureViewLinksIsMutable();
        viewLinks_.set(index, builderForValue.build());
        onChanged();
      } else {
        viewLinksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder addViewLinks(com.sagas.meta.model.MetaViewLink value) {
      if (viewLinksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewLinksIsMutable();
        viewLinks_.add(value);
        onChanged();
      } else {
        viewLinksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder addViewLinks(
        int index, com.sagas.meta.model.MetaViewLink value) {
      if (viewLinksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewLinksIsMutable();
        viewLinks_.add(index, value);
        onChanged();
      } else {
        viewLinksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder addViewLinks(
        com.sagas.meta.model.MetaViewLink.Builder builderForValue) {
      if (viewLinksBuilder_ == null) {
        ensureViewLinksIsMutable();
        viewLinks_.add(builderForValue.build());
        onChanged();
      } else {
        viewLinksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder addViewLinks(
        int index, com.sagas.meta.model.MetaViewLink.Builder builderForValue) {
      if (viewLinksBuilder_ == null) {
        ensureViewLinksIsMutable();
        viewLinks_.add(index, builderForValue.build());
        onChanged();
      } else {
        viewLinksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder addAllViewLinks(
        java.lang.Iterable<? extends com.sagas.meta.model.MetaViewLink> values) {
      if (viewLinksBuilder_ == null) {
        ensureViewLinksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, viewLinks_);
        onChanged();
      } else {
        viewLinksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder clearViewLinks() {
      if (viewLinksBuilder_ == null) {
        viewLinks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        viewLinksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public Builder removeViewLinks(int index) {
      if (viewLinksBuilder_ == null) {
        ensureViewLinksIsMutable();
        viewLinks_.remove(index);
        onChanged();
      } else {
        viewLinksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public com.sagas.meta.model.MetaViewLink.Builder getViewLinksBuilder(
        int index) {
      return getViewLinksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public com.sagas.meta.model.MetaViewLinkOrBuilder getViewLinksOrBuilder(
        int index) {
      if (viewLinksBuilder_ == null) {
        return viewLinks_.get(index);  } else {
        return viewLinksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public java.util.List<? extends com.sagas.meta.model.MetaViewLinkOrBuilder> 
         getViewLinksOrBuilderList() {
      if (viewLinksBuilder_ != null) {
        return viewLinksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(viewLinks_);
      }
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public com.sagas.meta.model.MetaViewLink.Builder addViewLinksBuilder() {
      return getViewLinksFieldBuilder().addBuilder(
          com.sagas.meta.model.MetaViewLink.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public com.sagas.meta.model.MetaViewLink.Builder addViewLinksBuilder(
        int index) {
      return getViewLinksFieldBuilder().addBuilder(
          index, com.sagas.meta.model.MetaViewLink.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaViewLink viewLinks = 6;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaViewLink.Builder> 
         getViewLinksBuilderList() {
      return getViewLinksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaViewLink, com.sagas.meta.model.MetaViewLink.Builder, com.sagas.meta.model.MetaViewLinkOrBuilder> 
        getViewLinksFieldBuilder() {
      if (viewLinksBuilder_ == null) {
        viewLinksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sagas.meta.model.MetaViewLink, com.sagas.meta.model.MetaViewLink.Builder, com.sagas.meta.model.MetaViewLinkOrBuilder>(
                viewLinks_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        viewLinks_ = null;
      }
      return viewLinksBuilder_;
    }

    private java.util.List<com.sagas.meta.model.MetaField> groupBys_ =
      java.util.Collections.emptyList();
    private void ensureGroupBysIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        groupBys_ = new java.util.ArrayList<com.sagas.meta.model.MetaField>(groupBys_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaField, com.sagas.meta.model.MetaField.Builder, com.sagas.meta.model.MetaFieldOrBuilder> groupBysBuilder_;

    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaField> getGroupBysList() {
      if (groupBysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groupBys_);
      } else {
        return groupBysBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public int getGroupBysCount() {
      if (groupBysBuilder_ == null) {
        return groupBys_.size();
      } else {
        return groupBysBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public com.sagas.meta.model.MetaField getGroupBys(int index) {
      if (groupBysBuilder_ == null) {
        return groupBys_.get(index);
      } else {
        return groupBysBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder setGroupBys(
        int index, com.sagas.meta.model.MetaField value) {
      if (groupBysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupBysIsMutable();
        groupBys_.set(index, value);
        onChanged();
      } else {
        groupBysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder setGroupBys(
        int index, com.sagas.meta.model.MetaField.Builder builderForValue) {
      if (groupBysBuilder_ == null) {
        ensureGroupBysIsMutable();
        groupBys_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupBysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder addGroupBys(com.sagas.meta.model.MetaField value) {
      if (groupBysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupBysIsMutable();
        groupBys_.add(value);
        onChanged();
      } else {
        groupBysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder addGroupBys(
        int index, com.sagas.meta.model.MetaField value) {
      if (groupBysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupBysIsMutable();
        groupBys_.add(index, value);
        onChanged();
      } else {
        groupBysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder addGroupBys(
        com.sagas.meta.model.MetaField.Builder builderForValue) {
      if (groupBysBuilder_ == null) {
        ensureGroupBysIsMutable();
        groupBys_.add(builderForValue.build());
        onChanged();
      } else {
        groupBysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder addGroupBys(
        int index, com.sagas.meta.model.MetaField.Builder builderForValue) {
      if (groupBysBuilder_ == null) {
        ensureGroupBysIsMutable();
        groupBys_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupBysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder addAllGroupBys(
        java.lang.Iterable<? extends com.sagas.meta.model.MetaField> values) {
      if (groupBysBuilder_ == null) {
        ensureGroupBysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupBys_);
        onChanged();
      } else {
        groupBysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder clearGroupBys() {
      if (groupBysBuilder_ == null) {
        groupBys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        groupBysBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public Builder removeGroupBys(int index) {
      if (groupBysBuilder_ == null) {
        ensureGroupBysIsMutable();
        groupBys_.remove(index);
        onChanged();
      } else {
        groupBysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public com.sagas.meta.model.MetaField.Builder getGroupBysBuilder(
        int index) {
      return getGroupBysFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public com.sagas.meta.model.MetaFieldOrBuilder getGroupBysOrBuilder(
        int index) {
      if (groupBysBuilder_ == null) {
        return groupBys_.get(index);  } else {
        return groupBysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public java.util.List<? extends com.sagas.meta.model.MetaFieldOrBuilder> 
         getGroupBysOrBuilderList() {
      if (groupBysBuilder_ != null) {
        return groupBysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groupBys_);
      }
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public com.sagas.meta.model.MetaField.Builder addGroupBysBuilder() {
      return getGroupBysFieldBuilder().addBuilder(
          com.sagas.meta.model.MetaField.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public com.sagas.meta.model.MetaField.Builder addGroupBysBuilder(
        int index) {
      return getGroupBysFieldBuilder().addBuilder(
          index, com.sagas.meta.model.MetaField.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaField groupBys = 7;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaField.Builder> 
         getGroupBysBuilderList() {
      return getGroupBysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaField, com.sagas.meta.model.MetaField.Builder, com.sagas.meta.model.MetaFieldOrBuilder> 
        getGroupBysFieldBuilder() {
      if (groupBysBuilder_ == null) {
        groupBysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sagas.meta.model.MetaField, com.sagas.meta.model.MetaField.Builder, com.sagas.meta.model.MetaFieldOrBuilder>(
                groupBys_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        groupBys_ = null;
      }
      return groupBysBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.MetaViewEntity)
  }

  // @@protoc_insertion_point(class_scope:model.MetaViewEntity)
  private static final com.sagas.meta.model.MetaViewEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.MetaViewEntity();
  }

  public static com.sagas.meta.model.MetaViewEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaViewEntity>
      PARSER = new com.google.protobuf.AbstractParser<MetaViewEntity>() {
    @java.lang.Override
    public MetaViewEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetaViewEntity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaViewEntity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaViewEntity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.MetaViewEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

