// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forms.proto

package com.sagas.meta.model;

public interface MetaFieldMappingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaFieldMappings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .model.MetaFieldMapping fields = 1;</code>
   */
  java.util.List<com.sagas.meta.model.MetaFieldMapping> 
      getFieldsList();
  /**
   * <code>repeated .model.MetaFieldMapping fields = 1;</code>
   */
  com.sagas.meta.model.MetaFieldMapping getFields(int index);
  /**
   * <code>repeated .model.MetaFieldMapping fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .model.MetaFieldMapping fields = 1;</code>
   */
  java.util.List<? extends com.sagas.meta.model.MetaFieldMappingOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .model.MetaFieldMapping fields = 1;</code>
   */
  com.sagas.meta.model.MetaFieldMappingOrBuilder getFieldsOrBuilder(
      int index);
}
