// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forms.proto

package com.sagas.meta.model;

public interface MetaFieldMappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaFieldMapping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * extract from title original
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   * extract from title original
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string fieldName = 2;</code>
   */
  java.lang.String getFieldName();
  /**
   * <code>string fieldName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <code>string fieldTitle = 3;</code>
   */
  java.lang.String getFieldTitle();
  /**
   * <code>string fieldTitle = 3;</code>
   */
  com.google.protobuf.ByteString
      getFieldTitleBytes();

  /**
   * <code>string fieldTitleOriginal = 4;</code>
   */
  java.lang.String getFieldTitleOriginal();
  /**
   * <code>string fieldTitleOriginal = 4;</code>
   */
  com.google.protobuf.ByteString
      getFieldTitleOriginalBytes();

  /**
   * <code>string formUri = 5;</code>
   */
  java.lang.String getFormUri();
  /**
   * <code>string formUri = 5;</code>
   */
  com.google.protobuf.ByteString
      getFormUriBytes();
}
