// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.MetaPermission}
 */
public  final class MetaPermission extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.MetaPermission)
    MetaPermissionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaPermission.newBuilder() to construct.
  private MetaPermission(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaPermission() {
    permissionType_ = 0;
    serviceModel_ = "";
    nameOrRole_ = "";
    action_ = "";
    permissionServiceName_ = "";
    permissionResourceDesc_ = "";
    auth_ = false;
    clazz_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetaPermission(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            permissionType_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceModel_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nameOrRole_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            permissionServiceName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            permissionResourceDesc_ = s;
            break;
          }
          case 56: {

            auth_ = input.readBool();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            clazz_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaPermission_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaPermission_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.MetaPermission.class, com.sagas.meta.model.MetaPermission.Builder.class);
  }

  public static final int PERMISSIONTYPE_FIELD_NUMBER = 1;
  private int permissionType_;
  /**
   * <code>int32 permissionType = 1;</code>
   */
  public int getPermissionType() {
    return permissionType_;
  }

  public static final int SERVICEMODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object serviceModel_;
  /**
   * <code>string serviceModel = 2;</code>
   */
  public java.lang.String getServiceModel() {
    java.lang.Object ref = serviceModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceModel_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceModel = 2;</code>
   */
  public com.google.protobuf.ByteString
      getServiceModelBytes() {
    java.lang.Object ref = serviceModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMEORROLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object nameOrRole_;
  /**
   * <code>string nameOrRole = 3;</code>
   */
  public java.lang.String getNameOrRole() {
    java.lang.Object ref = nameOrRole_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameOrRole_ = s;
      return s;
    }
  }
  /**
   * <code>string nameOrRole = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameOrRoleBytes() {
    java.lang.Object ref = nameOrRole_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameOrRole_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 4;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 4;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSIONSERVICENAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object permissionServiceName_;
  /**
   * <code>string permissionServiceName = 5;</code>
   */
  public java.lang.String getPermissionServiceName() {
    java.lang.Object ref = permissionServiceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      permissionServiceName_ = s;
      return s;
    }
  }
  /**
   * <code>string permissionServiceName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPermissionServiceNameBytes() {
    java.lang.Object ref = permissionServiceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      permissionServiceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSIONRESOURCEDESC_FIELD_NUMBER = 6;
  private volatile java.lang.Object permissionResourceDesc_;
  /**
   * <code>string permissionResourceDesc = 6;</code>
   */
  public java.lang.String getPermissionResourceDesc() {
    java.lang.Object ref = permissionResourceDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      permissionResourceDesc_ = s;
      return s;
    }
  }
  /**
   * <code>string permissionResourceDesc = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPermissionResourceDescBytes() {
    java.lang.Object ref = permissionResourceDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      permissionResourceDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTH_FIELD_NUMBER = 7;
  private boolean auth_;
  /**
   * <code>bool auth = 7;</code>
   */
  public boolean getAuth() {
    return auth_;
  }

  public static final int CLAZZ_FIELD_NUMBER = 8;
  private volatile java.lang.Object clazz_;
  /**
   * <code>string clazz = 8;</code>
   */
  public java.lang.String getClazz() {
    java.lang.Object ref = clazz_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clazz_ = s;
      return s;
    }
  }
  /**
   * <code>string clazz = 8;</code>
   */
  public com.google.protobuf.ByteString
      getClazzBytes() {
    java.lang.Object ref = clazz_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clazz_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (permissionType_ != 0) {
      output.writeInt32(1, permissionType_);
    }
    if (!getServiceModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceModel_);
    }
    if (!getNameOrRoleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nameOrRole_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, action_);
    }
    if (!getPermissionServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, permissionServiceName_);
    }
    if (!getPermissionResourceDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, permissionResourceDesc_);
    }
    if (auth_ != false) {
      output.writeBool(7, auth_);
    }
    if (!getClazzBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, clazz_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (permissionType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, permissionType_);
    }
    if (!getServiceModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceModel_);
    }
    if (!getNameOrRoleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nameOrRole_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, action_);
    }
    if (!getPermissionServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, permissionServiceName_);
    }
    if (!getPermissionResourceDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, permissionResourceDesc_);
    }
    if (auth_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, auth_);
    }
    if (!getClazzBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, clazz_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.MetaPermission)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.MetaPermission other = (com.sagas.meta.model.MetaPermission) obj;

    boolean result = true;
    result = result && (getPermissionType()
        == other.getPermissionType());
    result = result && getServiceModel()
        .equals(other.getServiceModel());
    result = result && getNameOrRole()
        .equals(other.getNameOrRole());
    result = result && getAction()
        .equals(other.getAction());
    result = result && getPermissionServiceName()
        .equals(other.getPermissionServiceName());
    result = result && getPermissionResourceDesc()
        .equals(other.getPermissionResourceDesc());
    result = result && (getAuth()
        == other.getAuth());
    result = result && getClazz()
        .equals(other.getClazz());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERMISSIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPermissionType();
    hash = (37 * hash) + SERVICEMODEL_FIELD_NUMBER;
    hash = (53 * hash) + getServiceModel().hashCode();
    hash = (37 * hash) + NAMEORROLE_FIELD_NUMBER;
    hash = (53 * hash) + getNameOrRole().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + PERMISSIONSERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPermissionServiceName().hashCode();
    hash = (37 * hash) + PERMISSIONRESOURCEDESC_FIELD_NUMBER;
    hash = (53 * hash) + getPermissionResourceDesc().hashCode();
    hash = (37 * hash) + AUTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAuth());
    hash = (37 * hash) + CLAZZ_FIELD_NUMBER;
    hash = (53 * hash) + getClazz().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.MetaPermission parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaPermission parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaPermission parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaPermission parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.MetaPermission prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.MetaPermission}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.MetaPermission)
      com.sagas.meta.model.MetaPermissionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaPermission_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaPermission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.MetaPermission.class, com.sagas.meta.model.MetaPermission.Builder.class);
    }

    // Construct using com.sagas.meta.model.MetaPermission.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      permissionType_ = 0;

      serviceModel_ = "";

      nameOrRole_ = "";

      action_ = "";

      permissionServiceName_ = "";

      permissionResourceDesc_ = "";

      auth_ = false;

      clazz_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaPermission_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaPermission getDefaultInstanceForType() {
      return com.sagas.meta.model.MetaPermission.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaPermission build() {
      com.sagas.meta.model.MetaPermission result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaPermission buildPartial() {
      com.sagas.meta.model.MetaPermission result = new com.sagas.meta.model.MetaPermission(this);
      result.permissionType_ = permissionType_;
      result.serviceModel_ = serviceModel_;
      result.nameOrRole_ = nameOrRole_;
      result.action_ = action_;
      result.permissionServiceName_ = permissionServiceName_;
      result.permissionResourceDesc_ = permissionResourceDesc_;
      result.auth_ = auth_;
      result.clazz_ = clazz_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.MetaPermission) {
        return mergeFrom((com.sagas.meta.model.MetaPermission)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.MetaPermission other) {
      if (other == com.sagas.meta.model.MetaPermission.getDefaultInstance()) return this;
      if (other.getPermissionType() != 0) {
        setPermissionType(other.getPermissionType());
      }
      if (!other.getServiceModel().isEmpty()) {
        serviceModel_ = other.serviceModel_;
        onChanged();
      }
      if (!other.getNameOrRole().isEmpty()) {
        nameOrRole_ = other.nameOrRole_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getPermissionServiceName().isEmpty()) {
        permissionServiceName_ = other.permissionServiceName_;
        onChanged();
      }
      if (!other.getPermissionResourceDesc().isEmpty()) {
        permissionResourceDesc_ = other.permissionResourceDesc_;
        onChanged();
      }
      if (other.getAuth() != false) {
        setAuth(other.getAuth());
      }
      if (!other.getClazz().isEmpty()) {
        clazz_ = other.clazz_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.MetaPermission parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.MetaPermission) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int permissionType_ ;
    /**
     * <code>int32 permissionType = 1;</code>
     */
    public int getPermissionType() {
      return permissionType_;
    }
    /**
     * <code>int32 permissionType = 1;</code>
     */
    public Builder setPermissionType(int value) {
      
      permissionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 permissionType = 1;</code>
     */
    public Builder clearPermissionType() {
      
      permissionType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object serviceModel_ = "";
    /**
     * <code>string serviceModel = 2;</code>
     */
    public java.lang.String getServiceModel() {
      java.lang.Object ref = serviceModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceModel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceModelBytes() {
      java.lang.Object ref = serviceModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceModel = 2;</code>
     */
    public Builder setServiceModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceModel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceModel = 2;</code>
     */
    public Builder clearServiceModel() {
      
      serviceModel_ = getDefaultInstance().getServiceModel();
      onChanged();
      return this;
    }
    /**
     * <code>string serviceModel = 2;</code>
     */
    public Builder setServiceModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceModel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameOrRole_ = "";
    /**
     * <code>string nameOrRole = 3;</code>
     */
    public java.lang.String getNameOrRole() {
      java.lang.Object ref = nameOrRole_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameOrRole_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nameOrRole = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameOrRoleBytes() {
      java.lang.Object ref = nameOrRole_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameOrRole_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nameOrRole = 3;</code>
     */
    public Builder setNameOrRole(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameOrRole_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nameOrRole = 3;</code>
     */
    public Builder clearNameOrRole() {
      
      nameOrRole_ = getDefaultInstance().getNameOrRole();
      onChanged();
      return this;
    }
    /**
     * <code>string nameOrRole = 3;</code>
     */
    public Builder setNameOrRoleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameOrRole_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 4;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 4;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 4;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 4;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 4;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object permissionServiceName_ = "";
    /**
     * <code>string permissionServiceName = 5;</code>
     */
    public java.lang.String getPermissionServiceName() {
      java.lang.Object ref = permissionServiceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permissionServiceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string permissionServiceName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionServiceNameBytes() {
      java.lang.Object ref = permissionServiceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permissionServiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string permissionServiceName = 5;</code>
     */
    public Builder setPermissionServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      permissionServiceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string permissionServiceName = 5;</code>
     */
    public Builder clearPermissionServiceName() {
      
      permissionServiceName_ = getDefaultInstance().getPermissionServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string permissionServiceName = 5;</code>
     */
    public Builder setPermissionServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      permissionServiceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object permissionResourceDesc_ = "";
    /**
     * <code>string permissionResourceDesc = 6;</code>
     */
    public java.lang.String getPermissionResourceDesc() {
      java.lang.Object ref = permissionResourceDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permissionResourceDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string permissionResourceDesc = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionResourceDescBytes() {
      java.lang.Object ref = permissionResourceDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permissionResourceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string permissionResourceDesc = 6;</code>
     */
    public Builder setPermissionResourceDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      permissionResourceDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string permissionResourceDesc = 6;</code>
     */
    public Builder clearPermissionResourceDesc() {
      
      permissionResourceDesc_ = getDefaultInstance().getPermissionResourceDesc();
      onChanged();
      return this;
    }
    /**
     * <code>string permissionResourceDesc = 6;</code>
     */
    public Builder setPermissionResourceDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      permissionResourceDesc_ = value;
      onChanged();
      return this;
    }

    private boolean auth_ ;
    /**
     * <code>bool auth = 7;</code>
     */
    public boolean getAuth() {
      return auth_;
    }
    /**
     * <code>bool auth = 7;</code>
     */
    public Builder setAuth(boolean value) {
      
      auth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool auth = 7;</code>
     */
    public Builder clearAuth() {
      
      auth_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object clazz_ = "";
    /**
     * <code>string clazz = 8;</code>
     */
    public java.lang.String getClazz() {
      java.lang.Object ref = clazz_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clazz_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clazz = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClazzBytes() {
      java.lang.Object ref = clazz_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clazz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clazz = 8;</code>
     */
    public Builder setClazz(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clazz_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clazz = 8;</code>
     */
    public Builder clearClazz() {
      
      clazz_ = getDefaultInstance().getClazz();
      onChanged();
      return this;
    }
    /**
     * <code>string clazz = 8;</code>
     */
    public Builder setClazzBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clazz_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.MetaPermission)
  }

  // @@protoc_insertion_point(class_scope:model.MetaPermission)
  private static final com.sagas.meta.model.MetaPermission DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.MetaPermission();
  }

  public static com.sagas.meta.model.MetaPermission getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaPermission>
      PARSER = new com.google.protobuf.AbstractParser<MetaPermission>() {
    @java.lang.Override
    public MetaPermission parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetaPermission(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaPermission> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaPermission> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.MetaPermission getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

