// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.MetaViewLink}
 */
public  final class MetaViewLink extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.MetaViewLink)
    MetaViewLinkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaViewLink.newBuilder() to construct.
  private MetaViewLink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaViewLink() {
    entityAlias_ = "";
    relEntityAlias_ = "";
    relOptional_ = false;
    keyMaps_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetaViewLink(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            entityAlias_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            relEntityAlias_ = s;
            break;
          }
          case 24: {

            relOptional_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              keyMaps_ = new java.util.ArrayList<com.sagas.meta.model.MetaKeyMap>();
              mutable_bitField0_ |= 0x00000008;
            }
            keyMaps_.add(
                input.readMessage(com.sagas.meta.model.MetaKeyMap.parser(), extensionRegistry));
            break;
          }
          case 42: {
            com.sagas.meta.model.MetaViewEntityCondition.Builder subBuilder = null;
            if (viewEntityCondition_ != null) {
              subBuilder = viewEntityCondition_.toBuilder();
            }
            viewEntityCondition_ = input.readMessage(com.sagas.meta.model.MetaViewEntityCondition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(viewEntityCondition_);
              viewEntityCondition_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        keyMaps_ = java.util.Collections.unmodifiableList(keyMaps_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewLink_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewLink_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.MetaViewLink.class, com.sagas.meta.model.MetaViewLink.Builder.class);
  }

  private int bitField0_;
  public static final int ENTITYALIAS_FIELD_NUMBER = 1;
  private volatile java.lang.Object entityAlias_;
  /**
   * <code>string entityAlias = 1;</code>
   */
  public java.lang.String getEntityAlias() {
    java.lang.Object ref = entityAlias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityAlias_ = s;
      return s;
    }
  }
  /**
   * <code>string entityAlias = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEntityAliasBytes() {
    java.lang.Object ref = entityAlias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityAlias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELENTITYALIAS_FIELD_NUMBER = 2;
  private volatile java.lang.Object relEntityAlias_;
  /**
   * <code>string relEntityAlias = 2;</code>
   */
  public java.lang.String getRelEntityAlias() {
    java.lang.Object ref = relEntityAlias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relEntityAlias_ = s;
      return s;
    }
  }
  /**
   * <code>string relEntityAlias = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRelEntityAliasBytes() {
    java.lang.Object ref = relEntityAlias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relEntityAlias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELOPTIONAL_FIELD_NUMBER = 3;
  private boolean relOptional_;
  /**
   * <code>bool relOptional = 3;</code>
   */
  public boolean getRelOptional() {
    return relOptional_;
  }

  public static final int KEYMAPS_FIELD_NUMBER = 4;
  private java.util.List<com.sagas.meta.model.MetaKeyMap> keyMaps_;
  /**
   * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
   */
  public java.util.List<com.sagas.meta.model.MetaKeyMap> getKeyMapsList() {
    return keyMaps_;
  }
  /**
   * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
   */
  public java.util.List<? extends com.sagas.meta.model.MetaKeyMapOrBuilder> 
      getKeyMapsOrBuilderList() {
    return keyMaps_;
  }
  /**
   * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
   */
  public int getKeyMapsCount() {
    return keyMaps_.size();
  }
  /**
   * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
   */
  public com.sagas.meta.model.MetaKeyMap getKeyMaps(int index) {
    return keyMaps_.get(index);
  }
  /**
   * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
   */
  public com.sagas.meta.model.MetaKeyMapOrBuilder getKeyMapsOrBuilder(
      int index) {
    return keyMaps_.get(index);
  }

  public static final int VIEWENTITYCONDITION_FIELD_NUMBER = 5;
  private com.sagas.meta.model.MetaViewEntityCondition viewEntityCondition_;
  /**
   * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
   */
  public boolean hasViewEntityCondition() {
    return viewEntityCondition_ != null;
  }
  /**
   * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
   */
  public com.sagas.meta.model.MetaViewEntityCondition getViewEntityCondition() {
    return viewEntityCondition_ == null ? com.sagas.meta.model.MetaViewEntityCondition.getDefaultInstance() : viewEntityCondition_;
  }
  /**
   * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
   */
  public com.sagas.meta.model.MetaViewEntityConditionOrBuilder getViewEntityConditionOrBuilder() {
    return getViewEntityCondition();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEntityAliasBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entityAlias_);
    }
    if (!getRelEntityAliasBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relEntityAlias_);
    }
    if (relOptional_ != false) {
      output.writeBool(3, relOptional_);
    }
    for (int i = 0; i < keyMaps_.size(); i++) {
      output.writeMessage(4, keyMaps_.get(i));
    }
    if (viewEntityCondition_ != null) {
      output.writeMessage(5, getViewEntityCondition());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEntityAliasBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entityAlias_);
    }
    if (!getRelEntityAliasBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relEntityAlias_);
    }
    if (relOptional_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, relOptional_);
    }
    for (int i = 0; i < keyMaps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, keyMaps_.get(i));
    }
    if (viewEntityCondition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getViewEntityCondition());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.MetaViewLink)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.MetaViewLink other = (com.sagas.meta.model.MetaViewLink) obj;

    boolean result = true;
    result = result && getEntityAlias()
        .equals(other.getEntityAlias());
    result = result && getRelEntityAlias()
        .equals(other.getRelEntityAlias());
    result = result && (getRelOptional()
        == other.getRelOptional());
    result = result && getKeyMapsList()
        .equals(other.getKeyMapsList());
    result = result && (hasViewEntityCondition() == other.hasViewEntityCondition());
    if (hasViewEntityCondition()) {
      result = result && getViewEntityCondition()
          .equals(other.getViewEntityCondition());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITYALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getEntityAlias().hashCode();
    hash = (37 * hash) + RELENTITYALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getRelEntityAlias().hashCode();
    hash = (37 * hash) + RELOPTIONAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRelOptional());
    if (getKeyMapsCount() > 0) {
      hash = (37 * hash) + KEYMAPS_FIELD_NUMBER;
      hash = (53 * hash) + getKeyMapsList().hashCode();
    }
    if (hasViewEntityCondition()) {
      hash = (37 * hash) + VIEWENTITYCONDITION_FIELD_NUMBER;
      hash = (53 * hash) + getViewEntityCondition().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.MetaViewLink parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaViewLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.MetaViewLink prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.MetaViewLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.MetaViewLink)
      com.sagas.meta.model.MetaViewLinkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewLink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewLink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.MetaViewLink.class, com.sagas.meta.model.MetaViewLink.Builder.class);
    }

    // Construct using com.sagas.meta.model.MetaViewLink.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeyMapsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      entityAlias_ = "";

      relEntityAlias_ = "";

      relOptional_ = false;

      if (keyMapsBuilder_ == null) {
        keyMaps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        keyMapsBuilder_.clear();
      }
      if (viewEntityConditionBuilder_ == null) {
        viewEntityCondition_ = null;
      } else {
        viewEntityCondition_ = null;
        viewEntityConditionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Metainfo.internal_static_model_MetaViewLink_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewLink getDefaultInstanceForType() {
      return com.sagas.meta.model.MetaViewLink.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewLink build() {
      com.sagas.meta.model.MetaViewLink result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaViewLink buildPartial() {
      com.sagas.meta.model.MetaViewLink result = new com.sagas.meta.model.MetaViewLink(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.entityAlias_ = entityAlias_;
      result.relEntityAlias_ = relEntityAlias_;
      result.relOptional_ = relOptional_;
      if (keyMapsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          keyMaps_ = java.util.Collections.unmodifiableList(keyMaps_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.keyMaps_ = keyMaps_;
      } else {
        result.keyMaps_ = keyMapsBuilder_.build();
      }
      if (viewEntityConditionBuilder_ == null) {
        result.viewEntityCondition_ = viewEntityCondition_;
      } else {
        result.viewEntityCondition_ = viewEntityConditionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.MetaViewLink) {
        return mergeFrom((com.sagas.meta.model.MetaViewLink)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.MetaViewLink other) {
      if (other == com.sagas.meta.model.MetaViewLink.getDefaultInstance()) return this;
      if (!other.getEntityAlias().isEmpty()) {
        entityAlias_ = other.entityAlias_;
        onChanged();
      }
      if (!other.getRelEntityAlias().isEmpty()) {
        relEntityAlias_ = other.relEntityAlias_;
        onChanged();
      }
      if (other.getRelOptional() != false) {
        setRelOptional(other.getRelOptional());
      }
      if (keyMapsBuilder_ == null) {
        if (!other.keyMaps_.isEmpty()) {
          if (keyMaps_.isEmpty()) {
            keyMaps_ = other.keyMaps_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureKeyMapsIsMutable();
            keyMaps_.addAll(other.keyMaps_);
          }
          onChanged();
        }
      } else {
        if (!other.keyMaps_.isEmpty()) {
          if (keyMapsBuilder_.isEmpty()) {
            keyMapsBuilder_.dispose();
            keyMapsBuilder_ = null;
            keyMaps_ = other.keyMaps_;
            bitField0_ = (bitField0_ & ~0x00000008);
            keyMapsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeyMapsFieldBuilder() : null;
          } else {
            keyMapsBuilder_.addAllMessages(other.keyMaps_);
          }
        }
      }
      if (other.hasViewEntityCondition()) {
        mergeViewEntityCondition(other.getViewEntityCondition());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.MetaViewLink parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.MetaViewLink) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object entityAlias_ = "";
    /**
     * <code>string entityAlias = 1;</code>
     */
    public java.lang.String getEntityAlias() {
      java.lang.Object ref = entityAlias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityAlias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entityAlias = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEntityAliasBytes() {
      java.lang.Object ref = entityAlias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityAlias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entityAlias = 1;</code>
     */
    public Builder setEntityAlias(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entityAlias_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entityAlias = 1;</code>
     */
    public Builder clearEntityAlias() {
      
      entityAlias_ = getDefaultInstance().getEntityAlias();
      onChanged();
      return this;
    }
    /**
     * <code>string entityAlias = 1;</code>
     */
    public Builder setEntityAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entityAlias_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object relEntityAlias_ = "";
    /**
     * <code>string relEntityAlias = 2;</code>
     */
    public java.lang.String getRelEntityAlias() {
      java.lang.Object ref = relEntityAlias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relEntityAlias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relEntityAlias = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRelEntityAliasBytes() {
      java.lang.Object ref = relEntityAlias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relEntityAlias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relEntityAlias = 2;</code>
     */
    public Builder setRelEntityAlias(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      relEntityAlias_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string relEntityAlias = 2;</code>
     */
    public Builder clearRelEntityAlias() {
      
      relEntityAlias_ = getDefaultInstance().getRelEntityAlias();
      onChanged();
      return this;
    }
    /**
     * <code>string relEntityAlias = 2;</code>
     */
    public Builder setRelEntityAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      relEntityAlias_ = value;
      onChanged();
      return this;
    }

    private boolean relOptional_ ;
    /**
     * <code>bool relOptional = 3;</code>
     */
    public boolean getRelOptional() {
      return relOptional_;
    }
    /**
     * <code>bool relOptional = 3;</code>
     */
    public Builder setRelOptional(boolean value) {
      
      relOptional_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool relOptional = 3;</code>
     */
    public Builder clearRelOptional() {
      
      relOptional_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.sagas.meta.model.MetaKeyMap> keyMaps_ =
      java.util.Collections.emptyList();
    private void ensureKeyMapsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        keyMaps_ = new java.util.ArrayList<com.sagas.meta.model.MetaKeyMap>(keyMaps_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaKeyMap, com.sagas.meta.model.MetaKeyMap.Builder, com.sagas.meta.model.MetaKeyMapOrBuilder> keyMapsBuilder_;

    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaKeyMap> getKeyMapsList() {
      if (keyMapsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keyMaps_);
      } else {
        return keyMapsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public int getKeyMapsCount() {
      if (keyMapsBuilder_ == null) {
        return keyMaps_.size();
      } else {
        return keyMapsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public com.sagas.meta.model.MetaKeyMap getKeyMaps(int index) {
      if (keyMapsBuilder_ == null) {
        return keyMaps_.get(index);
      } else {
        return keyMapsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder setKeyMaps(
        int index, com.sagas.meta.model.MetaKeyMap value) {
      if (keyMapsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyMapsIsMutable();
        keyMaps_.set(index, value);
        onChanged();
      } else {
        keyMapsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder setKeyMaps(
        int index, com.sagas.meta.model.MetaKeyMap.Builder builderForValue) {
      if (keyMapsBuilder_ == null) {
        ensureKeyMapsIsMutable();
        keyMaps_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyMapsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder addKeyMaps(com.sagas.meta.model.MetaKeyMap value) {
      if (keyMapsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyMapsIsMutable();
        keyMaps_.add(value);
        onChanged();
      } else {
        keyMapsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder addKeyMaps(
        int index, com.sagas.meta.model.MetaKeyMap value) {
      if (keyMapsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyMapsIsMutable();
        keyMaps_.add(index, value);
        onChanged();
      } else {
        keyMapsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder addKeyMaps(
        com.sagas.meta.model.MetaKeyMap.Builder builderForValue) {
      if (keyMapsBuilder_ == null) {
        ensureKeyMapsIsMutable();
        keyMaps_.add(builderForValue.build());
        onChanged();
      } else {
        keyMapsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder addKeyMaps(
        int index, com.sagas.meta.model.MetaKeyMap.Builder builderForValue) {
      if (keyMapsBuilder_ == null) {
        ensureKeyMapsIsMutable();
        keyMaps_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyMapsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder addAllKeyMaps(
        java.lang.Iterable<? extends com.sagas.meta.model.MetaKeyMap> values) {
      if (keyMapsBuilder_ == null) {
        ensureKeyMapsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyMaps_);
        onChanged();
      } else {
        keyMapsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder clearKeyMaps() {
      if (keyMapsBuilder_ == null) {
        keyMaps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        keyMapsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public Builder removeKeyMaps(int index) {
      if (keyMapsBuilder_ == null) {
        ensureKeyMapsIsMutable();
        keyMaps_.remove(index);
        onChanged();
      } else {
        keyMapsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public com.sagas.meta.model.MetaKeyMap.Builder getKeyMapsBuilder(
        int index) {
      return getKeyMapsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public com.sagas.meta.model.MetaKeyMapOrBuilder getKeyMapsOrBuilder(
        int index) {
      if (keyMapsBuilder_ == null) {
        return keyMaps_.get(index);  } else {
        return keyMapsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public java.util.List<? extends com.sagas.meta.model.MetaKeyMapOrBuilder> 
         getKeyMapsOrBuilderList() {
      if (keyMapsBuilder_ != null) {
        return keyMapsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keyMaps_);
      }
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public com.sagas.meta.model.MetaKeyMap.Builder addKeyMapsBuilder() {
      return getKeyMapsFieldBuilder().addBuilder(
          com.sagas.meta.model.MetaKeyMap.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public com.sagas.meta.model.MetaKeyMap.Builder addKeyMapsBuilder(
        int index) {
      return getKeyMapsFieldBuilder().addBuilder(
          index, com.sagas.meta.model.MetaKeyMap.getDefaultInstance());
    }
    /**
     * <code>repeated .model.MetaKeyMap keyMaps = 4;</code>
     */
    public java.util.List<com.sagas.meta.model.MetaKeyMap.Builder> 
         getKeyMapsBuilderList() {
      return getKeyMapsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sagas.meta.model.MetaKeyMap, com.sagas.meta.model.MetaKeyMap.Builder, com.sagas.meta.model.MetaKeyMapOrBuilder> 
        getKeyMapsFieldBuilder() {
      if (keyMapsBuilder_ == null) {
        keyMapsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sagas.meta.model.MetaKeyMap, com.sagas.meta.model.MetaKeyMap.Builder, com.sagas.meta.model.MetaKeyMapOrBuilder>(
                keyMaps_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        keyMaps_ = null;
      }
      return keyMapsBuilder_;
    }

    private com.sagas.meta.model.MetaViewEntityCondition viewEntityCondition_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sagas.meta.model.MetaViewEntityCondition, com.sagas.meta.model.MetaViewEntityCondition.Builder, com.sagas.meta.model.MetaViewEntityConditionOrBuilder> viewEntityConditionBuilder_;
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public boolean hasViewEntityCondition() {
      return viewEntityConditionBuilder_ != null || viewEntityCondition_ != null;
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public com.sagas.meta.model.MetaViewEntityCondition getViewEntityCondition() {
      if (viewEntityConditionBuilder_ == null) {
        return viewEntityCondition_ == null ? com.sagas.meta.model.MetaViewEntityCondition.getDefaultInstance() : viewEntityCondition_;
      } else {
        return viewEntityConditionBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public Builder setViewEntityCondition(com.sagas.meta.model.MetaViewEntityCondition value) {
      if (viewEntityConditionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        viewEntityCondition_ = value;
        onChanged();
      } else {
        viewEntityConditionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public Builder setViewEntityCondition(
        com.sagas.meta.model.MetaViewEntityCondition.Builder builderForValue) {
      if (viewEntityConditionBuilder_ == null) {
        viewEntityCondition_ = builderForValue.build();
        onChanged();
      } else {
        viewEntityConditionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public Builder mergeViewEntityCondition(com.sagas.meta.model.MetaViewEntityCondition value) {
      if (viewEntityConditionBuilder_ == null) {
        if (viewEntityCondition_ != null) {
          viewEntityCondition_ =
            com.sagas.meta.model.MetaViewEntityCondition.newBuilder(viewEntityCondition_).mergeFrom(value).buildPartial();
        } else {
          viewEntityCondition_ = value;
        }
        onChanged();
      } else {
        viewEntityConditionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public Builder clearViewEntityCondition() {
      if (viewEntityConditionBuilder_ == null) {
        viewEntityCondition_ = null;
        onChanged();
      } else {
        viewEntityCondition_ = null;
        viewEntityConditionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public com.sagas.meta.model.MetaViewEntityCondition.Builder getViewEntityConditionBuilder() {
      
      onChanged();
      return getViewEntityConditionFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    public com.sagas.meta.model.MetaViewEntityConditionOrBuilder getViewEntityConditionOrBuilder() {
      if (viewEntityConditionBuilder_ != null) {
        return viewEntityConditionBuilder_.getMessageOrBuilder();
      } else {
        return viewEntityCondition_ == null ?
            com.sagas.meta.model.MetaViewEntityCondition.getDefaultInstance() : viewEntityCondition_;
      }
    }
    /**
     * <code>.model.MetaViewEntityCondition viewEntityCondition = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sagas.meta.model.MetaViewEntityCondition, com.sagas.meta.model.MetaViewEntityCondition.Builder, com.sagas.meta.model.MetaViewEntityConditionOrBuilder> 
        getViewEntityConditionFieldBuilder() {
      if (viewEntityConditionBuilder_ == null) {
        viewEntityConditionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sagas.meta.model.MetaViewEntityCondition, com.sagas.meta.model.MetaViewEntityCondition.Builder, com.sagas.meta.model.MetaViewEntityConditionOrBuilder>(
                getViewEntityCondition(),
                getParentForChildren(),
                isClean());
        viewEntityCondition_ = null;
      }
      return viewEntityConditionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.MetaViewLink)
  }

  // @@protoc_insertion_point(class_scope:model.MetaViewLink)
  private static final com.sagas.meta.model.MetaViewLink DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.MetaViewLink();
  }

  public static com.sagas.meta.model.MetaViewLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaViewLink>
      PARSER = new com.google.protobuf.AbstractParser<MetaViewLink>() {
    @java.lang.Override
    public MetaViewLink parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetaViewLink(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaViewLink> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaViewLink> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.MetaViewLink getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

