// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

public interface MetaQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string infoType = 1;</code>
   */
  java.lang.String getInfoType();
  /**
   * <code>string infoType = 1;</code>
   */
  com.google.protobuf.ByteString
      getInfoTypeBytes();

  /**
   * <code>string uri = 2;</code>
   */
  java.lang.String getUri();
  /**
   * <code>string uri = 2;</code>
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
