// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forms.proto

package com.sagas.meta.model;

public interface MetaTextAreaFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaTextAreaField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cols = 1;</code>
   */
  int getCols();

  /**
   * <code>int32 rows = 2;</code>
   */
  int getRows();

  /**
   * <code>string defaultValue = 3;</code>
   */
  java.lang.String getDefaultValue();
  /**
   * <code>string defaultValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getDefaultValueBytes();

  /**
   * <code>bool readonly = 4;</code>
   */
  boolean getReadonly();

  /**
   * <code>int32 maxLength = 5;</code>
   */
  int getMaxLength();
}
