// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metainfo.proto

package com.sagas.meta.model;

public interface MetaPermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.MetaPermission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 permissionType = 1;</code>
   */
  int getPermissionType();

  /**
   * <code>string serviceModel = 2;</code>
   */
  java.lang.String getServiceModel();
  /**
   * <code>string serviceModel = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceModelBytes();

  /**
   * <code>string nameOrRole = 3;</code>
   */
  java.lang.String getNameOrRole();
  /**
   * <code>string nameOrRole = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameOrRoleBytes();

  /**
   * <code>string action = 4;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 4;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string permissionServiceName = 5;</code>
   */
  java.lang.String getPermissionServiceName();
  /**
   * <code>string permissionServiceName = 5;</code>
   */
  com.google.protobuf.ByteString
      getPermissionServiceNameBytes();

  /**
   * <code>string permissionResourceDesc = 6;</code>
   */
  java.lang.String getPermissionResourceDesc();
  /**
   * <code>string permissionResourceDesc = 6;</code>
   */
  com.google.protobuf.ByteString
      getPermissionResourceDescBytes();

  /**
   * <code>bool auth = 7;</code>
   */
  boolean getAuth();

  /**
   * <code>string clazz = 8;</code>
   */
  java.lang.String getClazz();
  /**
   * <code>string clazz = 8;</code>
   */
  com.google.protobuf.ByteString
      getClazzBytes();
}
