// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forms.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.MetaTextAreaField}
 */
public  final class MetaTextAreaField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.MetaTextAreaField)
    MetaTextAreaFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetaTextAreaField.newBuilder() to construct.
  private MetaTextAreaField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaTextAreaField() {
    cols_ = 0;
    rows_ = 0;
    defaultValue_ = "";
    readonly_ = false;
    maxLength_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetaTextAreaField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            cols_ = input.readInt32();
            break;
          }
          case 16: {

            rows_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            defaultValue_ = s;
            break;
          }
          case 32: {

            readonly_ = input.readBool();
            break;
          }
          case 40: {

            maxLength_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Forms.internal_static_model_MetaTextAreaField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Forms.internal_static_model_MetaTextAreaField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.MetaTextAreaField.class, com.sagas.meta.model.MetaTextAreaField.Builder.class);
  }

  public static final int COLS_FIELD_NUMBER = 1;
  private int cols_;
  /**
   * <code>int32 cols = 1;</code>
   */
  public int getCols() {
    return cols_;
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  private int rows_;
  /**
   * <code>int32 rows = 2;</code>
   */
  public int getRows() {
    return rows_;
  }

  public static final int DEFAULTVALUE_FIELD_NUMBER = 3;
  private volatile java.lang.Object defaultValue_;
  /**
   * <code>string defaultValue = 3;</code>
   */
  public java.lang.String getDefaultValue() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultValue_ = s;
      return s;
    }
  }
  /**
   * <code>string defaultValue = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDefaultValueBytes() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READONLY_FIELD_NUMBER = 4;
  private boolean readonly_;
  /**
   * <code>bool readonly = 4;</code>
   */
  public boolean getReadonly() {
    return readonly_;
  }

  public static final int MAXLENGTH_FIELD_NUMBER = 5;
  private int maxLength_;
  /**
   * <code>int32 maxLength = 5;</code>
   */
  public int getMaxLength() {
    return maxLength_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cols_ != 0) {
      output.writeInt32(1, cols_);
    }
    if (rows_ != 0) {
      output.writeInt32(2, rows_);
    }
    if (!getDefaultValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, defaultValue_);
    }
    if (readonly_ != false) {
      output.writeBool(4, readonly_);
    }
    if (maxLength_ != 0) {
      output.writeInt32(5, maxLength_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cols_);
    }
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, rows_);
    }
    if (!getDefaultValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, defaultValue_);
    }
    if (readonly_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, readonly_);
    }
    if (maxLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxLength_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.MetaTextAreaField)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.MetaTextAreaField other = (com.sagas.meta.model.MetaTextAreaField) obj;

    boolean result = true;
    result = result && (getCols()
        == other.getCols());
    result = result && (getRows()
        == other.getRows());
    result = result && getDefaultValue()
        .equals(other.getDefaultValue());
    result = result && (getReadonly()
        == other.getReadonly());
    result = result && (getMaxLength()
        == other.getMaxLength());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLS_FIELD_NUMBER;
    hash = (53 * hash) + getCols();
    hash = (37 * hash) + ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getRows();
    hash = (37 * hash) + DEFAULTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultValue().hashCode();
    hash = (37 * hash) + READONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReadonly());
    hash = (37 * hash) + MAXLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getMaxLength();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.MetaTextAreaField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.MetaTextAreaField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.MetaTextAreaField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.MetaTextAreaField)
      com.sagas.meta.model.MetaTextAreaFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Forms.internal_static_model_MetaTextAreaField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Forms.internal_static_model_MetaTextAreaField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.MetaTextAreaField.class, com.sagas.meta.model.MetaTextAreaField.Builder.class);
    }

    // Construct using com.sagas.meta.model.MetaTextAreaField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cols_ = 0;

      rows_ = 0;

      defaultValue_ = "";

      readonly_ = false;

      maxLength_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Forms.internal_static_model_MetaTextAreaField_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaTextAreaField getDefaultInstanceForType() {
      return com.sagas.meta.model.MetaTextAreaField.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaTextAreaField build() {
      com.sagas.meta.model.MetaTextAreaField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.MetaTextAreaField buildPartial() {
      com.sagas.meta.model.MetaTextAreaField result = new com.sagas.meta.model.MetaTextAreaField(this);
      result.cols_ = cols_;
      result.rows_ = rows_;
      result.defaultValue_ = defaultValue_;
      result.readonly_ = readonly_;
      result.maxLength_ = maxLength_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.MetaTextAreaField) {
        return mergeFrom((com.sagas.meta.model.MetaTextAreaField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.MetaTextAreaField other) {
      if (other == com.sagas.meta.model.MetaTextAreaField.getDefaultInstance()) return this;
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (!other.getDefaultValue().isEmpty()) {
        defaultValue_ = other.defaultValue_;
        onChanged();
      }
      if (other.getReadonly() != false) {
        setReadonly(other.getReadonly());
      }
      if (other.getMaxLength() != 0) {
        setMaxLength(other.getMaxLength());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.MetaTextAreaField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.MetaTextAreaField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int cols_ ;
    /**
     * <code>int32 cols = 1;</code>
     */
    public int getCols() {
      return cols_;
    }
    /**
     * <code>int32 cols = 1;</code>
     */
    public Builder setCols(int value) {
      
      cols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cols = 1;</code>
     */
    public Builder clearCols() {
      
      cols_ = 0;
      onChanged();
      return this;
    }

    private int rows_ ;
    /**
     * <code>int32 rows = 2;</code>
     */
    public int getRows() {
      return rows_;
    }
    /**
     * <code>int32 rows = 2;</code>
     */
    public Builder setRows(int value) {
      
      rows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rows = 2;</code>
     */
    public Builder clearRows() {
      
      rows_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object defaultValue_ = "";
    /**
     * <code>string defaultValue = 3;</code>
     */
    public java.lang.String getDefaultValue() {
      java.lang.Object ref = defaultValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string defaultValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      java.lang.Object ref = defaultValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string defaultValue = 3;</code>
     */
    public Builder setDefaultValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string defaultValue = 3;</code>
     */
    public Builder clearDefaultValue() {
      
      defaultValue_ = getDefaultInstance().getDefaultValue();
      onChanged();
      return this;
    }
    /**
     * <code>string defaultValue = 3;</code>
     */
    public Builder setDefaultValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultValue_ = value;
      onChanged();
      return this;
    }

    private boolean readonly_ ;
    /**
     * <code>bool readonly = 4;</code>
     */
    public boolean getReadonly() {
      return readonly_;
    }
    /**
     * <code>bool readonly = 4;</code>
     */
    public Builder setReadonly(boolean value) {
      
      readonly_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool readonly = 4;</code>
     */
    public Builder clearReadonly() {
      
      readonly_ = false;
      onChanged();
      return this;
    }

    private int maxLength_ ;
    /**
     * <code>int32 maxLength = 5;</code>
     */
    public int getMaxLength() {
      return maxLength_;
    }
    /**
     * <code>int32 maxLength = 5;</code>
     */
    public Builder setMaxLength(int value) {
      
      maxLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxLength = 5;</code>
     */
    public Builder clearMaxLength() {
      
      maxLength_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.MetaTextAreaField)
  }

  // @@protoc_insertion_point(class_scope:model.MetaTextAreaField)
  private static final com.sagas.meta.model.MetaTextAreaField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.MetaTextAreaField();
  }

  public static com.sagas.meta.model.MetaTextAreaField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaTextAreaField>
      PARSER = new com.google.protobuf.AbstractParser<MetaTextAreaField>() {
    @java.lang.Override
    public MetaTextAreaField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetaTextAreaField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaTextAreaField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaTextAreaField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.MetaTextAreaField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

