// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.RsEntityReference}
 */
public  final class RsEntityReference extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.RsEntityReference)
    RsEntityReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RsEntityReference.newBuilder() to construct.
  private RsEntityReference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RsEntityReference() {
    entities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    views_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RsEntityReference(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              entities_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            entities_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              views_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            views_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        entities_ = entities_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        views_ = views_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Resources.internal_static_model_RsEntityReference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Resources.internal_static_model_RsEntityReference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.RsEntityReference.class, com.sagas.meta.model.RsEntityReference.Builder.class);
  }

  public static final int ENTITIES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList entities_;
  /**
   * <code>repeated string entities = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEntitiesList() {
    return entities_;
  }
  /**
   * <code>repeated string entities = 1;</code>
   */
  public int getEntitiesCount() {
    return entities_.size();
  }
  /**
   * <code>repeated string entities = 1;</code>
   */
  public java.lang.String getEntities(int index) {
    return entities_.get(index);
  }
  /**
   * <code>repeated string entities = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEntitiesBytes(int index) {
    return entities_.getByteString(index);
  }

  public static final int VIEWS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList views_;
  /**
   * <code>repeated string views = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getViewsList() {
    return views_;
  }
  /**
   * <code>repeated string views = 2;</code>
   */
  public int getViewsCount() {
    return views_.size();
  }
  /**
   * <code>repeated string views = 2;</code>
   */
  public java.lang.String getViews(int index) {
    return views_.get(index);
  }
  /**
   * <code>repeated string views = 2;</code>
   */
  public com.google.protobuf.ByteString
      getViewsBytes(int index) {
    return views_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entities_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entities_.getRaw(i));
    }
    for (int i = 0; i < views_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, views_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < entities_.size(); i++) {
        dataSize += computeStringSizeNoTag(entities_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEntitiesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < views_.size(); i++) {
        dataSize += computeStringSizeNoTag(views_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getViewsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.RsEntityReference)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.RsEntityReference other = (com.sagas.meta.model.RsEntityReference) obj;

    boolean result = true;
    result = result && getEntitiesList()
        .equals(other.getEntitiesList());
    result = result && getViewsList()
        .equals(other.getViewsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntitiesCount() > 0) {
      hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntitiesList().hashCode();
    }
    if (getViewsCount() > 0) {
      hash = (37 * hash) + VIEWS_FIELD_NUMBER;
      hash = (53 * hash) + getViewsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.RsEntityReference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.RsEntityReference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.RsEntityReference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.RsEntityReference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.RsEntityReference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.RsEntityReference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.RsEntityReference)
      com.sagas.meta.model.RsEntityReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Resources.internal_static_model_RsEntityReference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Resources.internal_static_model_RsEntityReference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.RsEntityReference.class, com.sagas.meta.model.RsEntityReference.Builder.class);
    }

    // Construct using com.sagas.meta.model.RsEntityReference.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      entities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      views_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Resources.internal_static_model_RsEntityReference_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.RsEntityReference getDefaultInstanceForType() {
      return com.sagas.meta.model.RsEntityReference.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.RsEntityReference build() {
      com.sagas.meta.model.RsEntityReference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.RsEntityReference buildPartial() {
      com.sagas.meta.model.RsEntityReference result = new com.sagas.meta.model.RsEntityReference(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        entities_ = entities_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.entities_ = entities_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        views_ = views_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.views_ = views_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.RsEntityReference) {
        return mergeFrom((com.sagas.meta.model.RsEntityReference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.RsEntityReference other) {
      if (other == com.sagas.meta.model.RsEntityReference.getDefaultInstance()) return this;
      if (!other.entities_.isEmpty()) {
        if (entities_.isEmpty()) {
          entities_ = other.entities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEntitiesIsMutable();
          entities_.addAll(other.entities_);
        }
        onChanged();
      }
      if (!other.views_.isEmpty()) {
        if (views_.isEmpty()) {
          views_ = other.views_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureViewsIsMutable();
          views_.addAll(other.views_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.RsEntityReference parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.RsEntityReference) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList entities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEntitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        entities_ = new com.google.protobuf.LazyStringArrayList(entities_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEntitiesList() {
      return entities_.getUnmodifiableView();
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public int getEntitiesCount() {
      return entities_.size();
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public java.lang.String getEntities(int index) {
      return entities_.get(index);
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEntitiesBytes(int index) {
      return entities_.getByteString(index);
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public Builder setEntities(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntitiesIsMutable();
      entities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public Builder addEntities(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntitiesIsMutable();
      entities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public Builder addAllEntities(
        java.lang.Iterable<java.lang.String> values) {
      ensureEntitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, entities_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public Builder clearEntities() {
      entities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entities = 1;</code>
     */
    public Builder addEntitiesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEntitiesIsMutable();
      entities_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList views_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureViewsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        views_ = new com.google.protobuf.LazyStringArrayList(views_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getViewsList() {
      return views_.getUnmodifiableView();
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public int getViewsCount() {
      return views_.size();
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public java.lang.String getViews(int index) {
      return views_.get(index);
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public com.google.protobuf.ByteString
        getViewsBytes(int index) {
      return views_.getByteString(index);
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public Builder setViews(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureViewsIsMutable();
      views_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public Builder addViews(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureViewsIsMutable();
      views_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public Builder addAllViews(
        java.lang.Iterable<java.lang.String> values) {
      ensureViewsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, views_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public Builder clearViews() {
      views_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string views = 2;</code>
     */
    public Builder addViewsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureViewsIsMutable();
      views_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.RsEntityReference)
  }

  // @@protoc_insertion_point(class_scope:model.RsEntityReference)
  private static final com.sagas.meta.model.RsEntityReference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.RsEntityReference();
  }

  public static com.sagas.meta.model.RsEntityReference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RsEntityReference>
      PARSER = new com.google.protobuf.AbstractParser<RsEntityReference>() {
    @java.lang.Override
    public RsEntityReference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RsEntityReference(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RsEntityReference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RsEntityReference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.RsEntityReference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

