// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package com.sagas.meta.model;

public interface RsEntityReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.RsEntityReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string entities = 1;</code>
   */
  java.util.List<java.lang.String>
      getEntitiesList();
  /**
   * <code>repeated string entities = 1;</code>
   */
  int getEntitiesCount();
  /**
   * <code>repeated string entities = 1;</code>
   */
  java.lang.String getEntities(int index);
  /**
   * <code>repeated string entities = 1;</code>
   */
  com.google.protobuf.ByteString
      getEntitiesBytes(int index);

  /**
   * <code>repeated string views = 2;</code>
   */
  java.util.List<java.lang.String>
      getViewsList();
  /**
   * <code>repeated string views = 2;</code>
   */
  int getViewsCount();
  /**
   * <code>repeated string views = 2;</code>
   */
  java.lang.String getViews(int index);
  /**
   * <code>repeated string views = 2;</code>
   */
  com.google.protobuf.ByteString
      getViewsBytes(int index);
}
