// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package com.sagas.meta.model;

public interface RsPropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.RsProperty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>map&lt;string, string&gt; values = 2;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, string&gt; values = 2;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getValues();
  /**
   * <code>map&lt;string, string&gt; values = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getValuesMap();
  /**
   * <code>map&lt;string, string&gt; values = 2;</code>
   */

  java.lang.String getValuesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; values = 2;</code>
   */

  java.lang.String getValuesOrThrow(
      java.lang.String key);

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
