// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: values.proto

package com.sagas.meta.model;

public interface TaIdBagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.TaIdBag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string ids = 1;</code>
   */
  java.util.List<java.lang.String>
      getIdsList();
  /**
   * <code>repeated string ids = 1;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated string ids = 1;</code>
   */
  java.lang.String getIds(int index);
  /**
   * <code>repeated string ids = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdsBytes(int index);
}
