// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: values.proto

package com.sagas.meta.model;

public interface TaStringEntriesMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.TaStringEntriesMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */
  boolean containsEntries(
      java.lang.String key);
  /**
   * Use {@link #getEntriesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries>
  getEntries();
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */
  java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries>
  getEntriesMap();
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  com.sagas.meta.model.TaStringEntries getEntriesOrDefault(
      java.lang.String key,
      com.sagas.meta.model.TaStringEntries defaultValue);
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  com.sagas.meta.model.TaStringEntries getEntriesOrThrow(
      java.lang.String key);
}
