// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: values.proto

package com.sagas.meta.model;

/**
 * Protobuf type {@code model.TaStringEntriesMap}
 */
public  final class TaStringEntriesMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.TaStringEntriesMap)
    TaStringEntriesMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaStringEntriesMap.newBuilder() to construct.
  private TaStringEntriesMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaStringEntriesMap() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaStringEntriesMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              entries_ = com.google.protobuf.MapField.newMapField(
                  EntriesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.sagas.meta.model.TaStringEntries>
            entries__ = input.readMessage(
                EntriesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            entries_.getMutableMap().put(
                entries__.getKey(), entries__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetEntries();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sagas.meta.model.TaStringEntriesMap.class, com.sagas.meta.model.TaStringEntriesMap.Builder.class);
  }

  public static final int ENTRIES_FIELD_NUMBER = 1;
  private static final class EntriesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.sagas.meta.model.TaStringEntries> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.sagas.meta.model.TaStringEntries>newDefaultInstance(
                com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_EntriesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.sagas.meta.model.TaStringEntries.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.sagas.meta.model.TaStringEntries> entries_;
  private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.TaStringEntries>
  internalGetEntries() {
    if (entries_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EntriesDefaultEntryHolder.defaultEntry);
    }
    return entries_;
  }

  public int getEntriesCount() {
    return internalGetEntries().getMap().size();
  }
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  public boolean containsEntries(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetEntries().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEntriesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> getEntries() {
    return getEntriesMap();
  }
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  public java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> getEntriesMap() {
    return internalGetEntries().getMap();
  }
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  public com.sagas.meta.model.TaStringEntries getEntriesOrDefault(
      java.lang.String key,
      com.sagas.meta.model.TaStringEntries defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> map =
        internalGetEntries().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * key is global id
   * </pre>
   *
   * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
   */

  public com.sagas.meta.model.TaStringEntries getEntriesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> map =
        internalGetEntries().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEntries(),
        EntriesDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.sagas.meta.model.TaStringEntries> entry
         : internalGetEntries().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.sagas.meta.model.TaStringEntries>
      entries__ = EntriesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sagas.meta.model.TaStringEntriesMap)) {
      return super.equals(obj);
    }
    com.sagas.meta.model.TaStringEntriesMap other = (com.sagas.meta.model.TaStringEntriesMap) obj;

    boolean result = true;
    result = result && internalGetEntries().equals(
        other.internalGetEntries());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetEntries().getMap().isEmpty()) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEntries().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sagas.meta.model.TaStringEntriesMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sagas.meta.model.TaStringEntriesMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.TaStringEntriesMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.TaStringEntriesMap)
      com.sagas.meta.model.TaStringEntriesMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetEntries();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableEntries();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sagas.meta.model.TaStringEntriesMap.class, com.sagas.meta.model.TaStringEntriesMap.Builder.class);
    }

    // Construct using com.sagas.meta.model.TaStringEntriesMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableEntries().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sagas.meta.model.Values.internal_static_model_TaStringEntriesMap_descriptor;
    }

    @java.lang.Override
    public com.sagas.meta.model.TaStringEntriesMap getDefaultInstanceForType() {
      return com.sagas.meta.model.TaStringEntriesMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.sagas.meta.model.TaStringEntriesMap build() {
      com.sagas.meta.model.TaStringEntriesMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sagas.meta.model.TaStringEntriesMap buildPartial() {
      com.sagas.meta.model.TaStringEntriesMap result = new com.sagas.meta.model.TaStringEntriesMap(this);
      int from_bitField0_ = bitField0_;
      result.entries_ = internalGetEntries();
      result.entries_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sagas.meta.model.TaStringEntriesMap) {
        return mergeFrom((com.sagas.meta.model.TaStringEntriesMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sagas.meta.model.TaStringEntriesMap other) {
      if (other == com.sagas.meta.model.TaStringEntriesMap.getDefaultInstance()) return this;
      internalGetMutableEntries().mergeFrom(
          other.internalGetEntries());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sagas.meta.model.TaStringEntriesMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sagas.meta.model.TaStringEntriesMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.sagas.meta.model.TaStringEntries> entries_;
    private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.TaStringEntries>
    internalGetEntries() {
      if (entries_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntriesDefaultEntryHolder.defaultEntry);
      }
      return entries_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.sagas.meta.model.TaStringEntries>
    internalGetMutableEntries() {
      onChanged();;
      if (entries_ == null) {
        entries_ = com.google.protobuf.MapField.newMapField(
            EntriesDefaultEntryHolder.defaultEntry);
      }
      if (!entries_.isMutable()) {
        entries_ = entries_.copy();
      }
      return entries_;
    }

    public int getEntriesCount() {
      return internalGetEntries().getMap().size();
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public boolean containsEntries(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetEntries().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntriesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> getEntries() {
      return getEntriesMap();
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> getEntriesMap() {
      return internalGetEntries().getMap();
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public com.sagas.meta.model.TaStringEntries getEntriesOrDefault(
        java.lang.String key,
        com.sagas.meta.model.TaStringEntries defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> map =
          internalGetEntries().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public com.sagas.meta.model.TaStringEntries getEntriesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> map =
          internalGetEntries().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEntries() {
      internalGetMutableEntries().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public Builder removeEntries(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEntries().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries>
    getMutableEntries() {
      return internalGetMutableEntries().getMutableMap();
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */
    public Builder putEntries(
        java.lang.String key,
        com.sagas.meta.model.TaStringEntries value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEntries().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * key is global id
     * </pre>
     *
     * <code>map&lt;string, .model.TaStringEntries&gt; entries = 1;</code>
     */

    public Builder putAllEntries(
        java.util.Map<java.lang.String, com.sagas.meta.model.TaStringEntries> values) {
      internalGetMutableEntries().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.TaStringEntriesMap)
  }

  // @@protoc_insertion_point(class_scope:model.TaStringEntriesMap)
  private static final com.sagas.meta.model.TaStringEntriesMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sagas.meta.model.TaStringEntriesMap();
  }

  public static com.sagas.meta.model.TaStringEntriesMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaStringEntriesMap>
      PARSER = new com.google.protobuf.AbstractParser<TaStringEntriesMap>() {
    @java.lang.Override
    public TaStringEntriesMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaStringEntriesMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaStringEntriesMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaStringEntriesMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sagas.meta.model.TaStringEntriesMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

