// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.sagas.meta.model;

public interface TextLangInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.TextLangInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lang = 1;</code>
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 1;</code>
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>float confidence = 3;</code>
   */
  float getConfidence();

  /**
   * <code>bool reliable = 4;</code>
   */
  boolean getReliable();
}
